### ISSUE TITLE
ch3 misisng Immutable declaration

### ISSUE THREAD

**Issue by syzer** [MostlyAdequate/mostly-adequate-guide#10]
in line:
var jobe = Immutable.Map({name:"Jobe", hp:20, team: "red"})
```var Immutable = require('immutable');```
is missing from code
maybe better to use Set, since is implemented in all modern browsers?

**Comment by DrBoolean** [comment]
Good call! I'm fine sticking with `Map` as it matches the object version quite closely. I also like the `set` function in the example.
