### ISSUE TITLE
Monad Exercise 2 answer differs on Windows

### ISSUE THREAD

**Issue by JoshSchreuder** [MostlyAdequate/mostly-adequate-guide#105]
I think the answer to exercise 2 of the monads chapter is different when running on Windows due to the path separators.

Answer given is:
`var ex2 = _.compose(chain(_.compose(pureLog, _.last, split('/'))), getFile);`

But for me the test fails like this:
```
AssertionError: expected 'logged D:\\Users\\jschreuder\\Documents\\mostly-adequate-guide\\code\\part2_exercises\\exercises\\monads\\monad_exercises.js' to equal 'logged monad_exercises.js'
```

I had to split on `\` to get the test to pass:
`var ex2 = _.compose(chain(_.compose(pureLog, _.last, split('\\'))), getFile);`

Might be worth switching up this exercise with some other task to avoid cross platform issues?

**Comment by xujihui1985** [comment]
use path.sep
```
_.compose(chain(_.compose(pureLog, _.last, split(path.sep))), getFile);
```

**Comment by DrBoolean** [comment]
Oh awesome. I should put a note in there.
