### ISSUE TITLE
Replace as many as possible custom fn's with `_`

### ISSUE THREAD

**Issue by DrBoolean** [MostlyAdequate/mostly-adequate-guide#108]
Prior definitions casually used throughout is causing confusion - especially in the case of `compose` where we define a non variadic version and then proceed to use the variadic one for the rest of the book.

Should replace as much as possible with ramda or lodash-fp

**Comment by gyzerok** [comment]
+1

**Comment by wadtech** [comment]
+1 

I came looking for this because the section was confusing to follow.

**Comment by guumaster** [comment]
IMO, Ramda is better suited for the book examples. The different order on `lodash-fp` are not documented, you need to know lodash API, and then figure which parameters order are changed.

**Comment by slikts** [comment]
+1 for Ramda; it would also bring the examples closer to practicality, since you wouldn't want to take the book's approach of rolling your own functions like compose when working in the real world.
