### ISSUE TITLE
How does the reduce call work in the reverse() example?

### ISSUE THREAD

**Issue by tsummerall** [MostlyAdequate/mostly-adequate-guide#109]
I can't find an implementation of `reduce()` that this line of code works with from your example:

`var reverse = reduce(function(acc, x){ return [x].concat(acc); }, []);`

Is it a typo or can you provide a link that would explain how this reverse function operates?

And, to demonstrate my further confusion, shouldn't `reverse` be in the form of a composable pure function with one argument, as in `reverse=function(x) {..}` in order to be used with `compose`?

**Comment by Bondifrench** [comment]
If you are talking from Chapter 5, reduce is actually `_.reduce()` from the [Ramda](http://ramdajs.com/0.17/docs/#reduce) library, which has been curried.

DrBoolean needs to prefix a few functions explicitly with `_.`, so it's obvious they are coming from a library.

**Comment by tsummerall** [comment]
Thanks! 

This construction is esoteric enough to non-Ramda users that a sidebar about how it operates would be worthwhile I think. As far as I can tell, the commonly-used underscore.js implementation of `reduce()` wouldn't allow this trick.

**Comment by DrBoolean** [comment]
I have a video available that talks about reduce: https://www.youtube.com/watch?v=JZSoPZUoR58

**Comment by tsummerall** [comment]
That's a great video, thanks!

**Comment by jirutka** [comment]
@DrBoolean Heh, funny thing: I know you from your talk “[Hey Underscore, You're Doing It Wrong!](https://www.youtube.com/watch?v=m3svKOdZijA),” but didn’t know that you are Dr. Boolean, until know!

**Comment by DrBoolean** [comment]
ha, yeah. My avatar is a disguise!

**Comment by kdamball** [comment]
@DrBoolean YOU'RE THAT DUDE FROM THE UNDERSCORE VIDEO?

**Comment by DrBoolean** [comment]
haha, yep!

**Comment by kdamball** [comment]
I know of a few parties later this evening, if you still need one!

**Comment by DrBoolean** [comment]
ha. Leave it to me to forever ask the world where the party's at.
