### ISSUE TITLE
EPUB errors as 'corrupt' in iBooks

### ISSUE THREAD

**Issue by barberousse** [MostlyAdequate/mostly-adequate-guide#114]
After adding the ePub to iBooks, either downloaded from Gitbook or built manually, on open, iBooks reports that "This file is corrupt" and closes the book for reading.

**Comment by DrBoolean** [comment]
Huh, this was happening before as well. Opening twice worked for me, but I'll have to figure out what in the world is causing that. Thanks for bring attention.

**Comment by barberousse** [comment]
Strangely, unmaintained [Kitabu](https://itunes.apple.com/us/app/kitabu/id492498910?mt=12) has no problem opening the epub file.

**Comment by rjakobsson** [comment]
I have a problem opening the file in iBooks.

**Comment by DrBoolean** [comment]
Me too now. I'm lost on how gitbook does this and what I need to change. Any help is appreciated if someone knows

**Comment by DrBoolean** [comment]
I might have just fixed this in commit 50b0d91

**Comment by barberousse** [comment]
Cloned HEAD and built epub that sucessfully opens in iBooks. Thanks for the
fix!

On Mon, Oct 19, 2015 at 12:15 PM, Brian Lonsdorf <notifications@github.com>
wrote:

> I might have just fixed this in commit 50b0d91
> <https://github.com/MostlyAdequate/mostly-adequate-guide/commit/50b0d91f41a2e49b061692838ccf57aa57c85b39>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MostlyAdequate/mostly-adequate-guide/issues/114#issuecomment-149285403>
> .
>



-- 
Benoît Barberousse
512.981.6578
