### ISSUE TITLE
IO in Chapter 8

### ISSUE THREAD

**Issue by dslaugh** [MostlyAdequate/mostly-adequate-guide#129]
The IO functor in chapter 8 is not working for me. When I console.log the output, I just get IO{}

edit: I just figured out that I needed to call __value() to get the result

**Comment by DrBoolean** [comment]
That trips a lot of people up. I'll add a footnote. Thanks!

**Comment by geohuz** [comment]
Am not sure if this is correct, I use console.log(io_window.__value()), but all I got is this:
```
Window {undefined: undefined, window: Window, NaN: NaN, xxxx: undefined, IO: function, …}
```

**Comment by geohuz** [comment]
Ok, I got it by rewriting the code like this:

```
//  io_window_ :: IO Window
var io_window = new IO(function(){ return window; });

var width = io_window.map(function(win){ return win.innerWidth });
console.log(width.__value());

var urls = io_window.map(R.prop('location')).map(R.prop('href')).map(R.split('/'));
console.log(urls.__value());
```
