### ISSUE TITLE
Translation to russian

### ISSUE THREAD

**Issue by maksimf** [MostlyAdequate/mostly-adequate-guide#149]
@DrBoolean Hi Brian! I've read and loved the guide very much. I would love to translate it to russian, can I do that?

**Comment by DrBoolean** [comment]
Wow, yeah! That'd be amazing.

So far, people have forked it (or made a new repo) and sent a pull request for a link under languages.

Exciting!

**Comment by maksimf** [comment]
@DrBoolean Thank you, I'll start then and send you a pull request as far as first chapter would be ready, is that ok?

**Comment by DrBoolean** [comment]
For sure!

**Comment by KtorZ** [comment]
Hey!
@maksimf is raising here a nice question / idea.
I also really enjoyed the guide, and, I'll be glad to help for a french translation. 
Do we need to setup maybe a bit of organisation and a common process about translations ? So that other interested could easily follow to translate it in other languages ?

**Comment by maksimf** [comment]
@KtorZ The process of forking the repo and then submitting PR with a language seems to be a good idea. Can you please expand your idea a bit?

**Comment by KtorZ** [comment]
Sure.
I am talking about having all translated versions in a same repository, organised in several folders like:

```
- en > chap1 chap2 chap3 ...
- ru > chap1 chap2 chap3 ...
- fr > ...
```
etc.

**Comment by DrBoolean** [comment]
I think that's a great idea. I also don't want to downplay the effort involved in translating. If it helps one's visibility to have duplicated/forked the book rather than committed to a subfolder, I'm all for it. Whatever I can do to make the effort more worthwhile.

**Comment by guumaster** [comment]
:+1: This is a great idea. 

Looking around I've found the boot [Pro Git 2](https://progit.org/) that is managed [here](https://github.com/progit) as an organization, with a repo per language (look for the progit2-* repos). And apparently is later built with some scripts. 

Taking that one as example, what I propose is the following: 

* Create an organization with the main repo (english version).
* Create a team to maintain the org daily operations, etc.
* Create a repo for each translation requested (as issues on the main repo), and a language specific team with permissions over that repo.
* Rinse/repeat last step per each requested language.

I think this is a better idea than a simple fork, as there is already more than 300 forks out there. If you like this idea, I'm up to collaborate on maintenance and also with the spanish translation.

**Comment by maksimf** [comment]
@guumaster Good idea! :+1:

**Comment by KtorZ** [comment]
Then, let's go?

**Comment by zerkms** [comment]
Guys, how are you going to keep the translations in sync?

After the very first modification for the original book the translation will become obsolete (or even incorrect).

**Comment by KtorZ** [comment]
Should we create specific tags on issues / PR to refer to those kind of changes?
And maybe, open issues in related repository to take those changes in account..

Otherwise, maybe could we just add a version number to each chapter. So that we can keep track about the correspondence between a translated chapter and the original one. Something like, `major` for an error or an important change in the text; `minor` about addition or comments and `patch` for typos and alignment stuff.

What do you think of that ?

**Comment by zerkms** [comment]
I personally think that the only way to do that is to have a tool that would allow to track changes on per-paragraph basis. Eg:

> Should we create specific tags on issues / PR to refer to those kind of changes?
> And maybe, open issues in related repositories to take those changes in account..

This is a single paragraph and let's say it was translated to French.

If any change was applied to it - it invalidates the translation and the translation must be reviewed and acknowledged before it turns into actual again.

Not sure if something like that even exists, but I can tell for sure that "specific tags on issues / PR to refer to those kind of changes?' will not work.

**Comment by guumaster** [comment]
Sounds complicated. We can use git instead. Each lang repo may have the english version as an upstream reference. Language maintainer may integrate it and update periodically.

**Comment by zerkms** [comment]
> Each lang repo may have the english version as an upstream reference. Language maintainer may integrate it and update periodically.

How would you know something becomes obsolete? Say, you pulled the upstream after 3 weeks. What would be the next step? How at this point one would say what must be re-translated/fixed (in case if it's code)?

Everything that is not constrained by software and is based on conventions will become out of sync eventually. What is worse - one wouldn't be able to tell if it's in actual state or not, without manual re-checking of *everything*.

PS: please take my comments with skepticism. I do agree that for someone translation might be the only way to read it, but translations that are out of sync (or that cannot be synced easily) may cause headache to both readers and further maintainers.

**Comment by maksimf** [comment]
Sounds like out of the scope of this issue, please feel free to open another if you want to talk about syncing translations, btw the draft of first chapter is ready: https://github.com/maksimf/mostly-adequate-guide-russian/pull/1

**Comment by maksimf** [comment]
@DrBoolean Chapter 1 is ready, should I create PR here to reference russian translation already? Or should I do that after few more chapters?

**Comment by DrBoolean** [comment]
PR it up! I added you to the org, but I'm not sure what rights you have at the moment

**Comment by maksimf** [comment]
@DrBoolean Done :-)
