### ISSUE TITLE
"brew cask install calibre" outputs error

### ISSUE THREAD

**Issue by JustFly1984** [MostlyAdequate/mostly-adequate-guide#155]
Error: Unknown command: cask

I really love your book. It is pleasure to wrap my mind around this functional javascript conceptions.

Thank you very much for your work.

**Comment by Deveritas** [comment]
You need to install homebrew-cask, by running `brew install caskroom/cask/brew-cask`

**Comment by JustFly1984** [comment]
Thanx, I'm new to brew)
