### ISSUE TITLE
I just don't understand...

### ISSUE THREAD

**Issue by Padam87** [MostlyAdequate/mostly-adequate-guide#160]
Hi,

Could you guys help me a bit? I'm an OOP guy, always have been, but lately I have been trying to wrap my head around FP. In some cases, I see the benefits, but some of the examples I saw (not necessarily in this book) seem very forced, and just ... wrong.

**1, Value object vs Service** In chapter 1, your examples give different results. Which is totally expected, since the 2 pieces of code are totally different. Stateful objects (value objects if you prefer) should not be used in arithmetic operations like the example suggests.

And that is my main problem with FP... a large portion of examples boils down to wrong usage of OOP code. (Mixing value objects, and services)

**2, Simplicity** Now this part is totally understandable, and attractive, but... how are you gonna be able to work with lets say 200.000 LoC ? I just don't see that happening.

IMO functional style programming can only be applied effectively on utility code. Am I looking at this wrong? A chapter cleaning this up would be very useful!

Excited to read rest of the book!

Thanks,
Adam

**Comment by rbtbar** [comment]
Hi,

ad 1. I think the OOP example in chapter 1 isn't 100% fair...

* OOP is about hiding "moving" parts
* FP is about writing systems with "no moving" parts

... and this is how I would try to explain a basic difference between OOP and FP. Just for the beginning...

ad 2. Extensible and maintanable code needs to backed by design patterns. Both programming paradigms have them and in both cases they are powerful:
* OOP offers SOLID principles
* FP supports compositional programming backed by category theory


Regards,
rb

**Comment by Padam87** [comment]
By "no moving parts" I assume you refer to the statelessness of FP. But in real use cases basically everything is stateful. Except for util functions - which are perfectly covered by static methods in OOP, and I don't see why that would merit an entirely different style of programming.

Yes, OOP without the SOLID principles wouln't be as good as it is. BUT... the most of the organizing power comes from the classes and namespaces. I don't see how composition is an equal alternative to that, most examples I've seen only provide syntatic sugar, not organization.

**Comment by DrBoolean** [comment]
The OO example is bad on purpose. The "who would write such a ghastly abomination" line is to explain that it's not supposed to be good, but I think people take that as OO sucks (which it doesn't).

You're totally right about Value objects (DDD fan?). It's not to troll or anything - the FP version is expected to hold properties so I wanted to contrast that as much as possible with crazy mutating state. 

As far as simplicity goes, I can only suggest you try to write a large system with FP to see how it holds up. Functions in modules feels like methods in objects as far as organization goes.

**Comment by HaQadosch** [comment]
I really good step by step exploration of functional/reactive is available freely http://web.mit.edu/alexmv/6.S184/sicp.pdf 
This book has its own cult and rightly so.
