### ISSUE TITLE
Examples in chapter 10 (in Laws)

### ISSUE THREAD

**Issue by rpominov** [MostlyAdequate/mostly-adequate-guide#161]
Hey, @DrBoolean! I just read chapter 10, it's great as always! Noticed couple of minor issues in examples.

### # 1

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch10.md#laws

```js
var tOfM = compose(Task.of, Maybe.of);
var assemble = _.compose(_.concat, _.concat);

liftA3(assemble, tOfM('Rainy Days'), tOfM(' and Mondays'), tOfM(' always get me down'));
// Task(Maybe(Rainy Days and Mondays always get me down))
```

I think `assemble` should be defined as:
```js
var assemble = liftA3(_.concat);
```

### # 2

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch10.md#interchange

```js
var v = Task.of(_.reverse);
var x = Task.of('Sparklehorse');

v.ap(Task.of(x)) == Task.of(function(f) { return f(x) }).ap(v)
```

Here `var x = Task.of('Sparklehorse');` should be `var x = 'Sparklehorse';`.

**Comment by DrBoolean** [comment]
Thank you! For #1, I think _.concat will get called prematurely since it partially applies during each `ap`. You're intuition is right and we could do it with `liftA3(curry3(_.concat))`, but it works as is. #2 is totally right, I'll update now. Thanks!

**Comment by rpominov** [comment]
I still don't understand how it will work. `_.compose(_.concat, _.concat)` creates a curried function that operates on arrays or strings, but `liftA3(assemble, tOfM...)` will call it with Maybies as arguments. Is that right?

`var assemble = liftA3(_.concat)` also won't work though. Because `_.concat` is two arity. So the correct implementation is:

```js
var assemble = liftA3(_.compose(_.concat, _.concat));
```

Btw, it was pretty tricky to grasp that `_.compose(_.concat, _.concat)` creates a 3-arity concat :)

**Comment by DrBoolean** [comment]
Yeah, that's a really bad example... I'll try to come up with something a little more digestible.

**Comment by rpominov** [comment]
I think I finally get it. I didn't know that some Maybe implementations include .concat() and when called call .concat() on wrapped value. The example should work with a Maybe like that. Although, if I remember correctly, it was stated somewhere in previous chapters that the implementation from [Folktale](https://github.com/folktale/) is used in the book. And it doesn't seem to include .concat() https://github.com/folktale/data.maybe/blob/master/lib/maybe.js

And yeah, the example in general seems a little to hard to grasp :)

**Comment by salper** [comment]
The current definition for `#1` in chapter 10 is: 
```javascript
var tOfM = compose(Task.of, Maybe.of);

liftA2(_.concat, tOfM('Rainy Days and Mondays'), tOfM(' always get me down'));
// Task(Maybe(Rainy Days and Mondays always get me down))
```

But using the book definition of `Maybe` and `data.task`, I can make it work using:
```javascript
const tOfM = compose(Task.of, Maybe.of);

const concatMap = curry((m1, m2) => liftA2(concat, m1, m2));

liftA2(concatMap, tOfM('Rainy Days and Mondays'), tOfM(' always get me down'))
  .fork(err => log('err', err), data => log('success', data));
// Task(Maybe(Rainy Days and Mondays always get me down))
````

Am I missing something ?

**Comment by DrBoolean** [comment]
Thanks @salper, yes I really need to get on fixing this. You're definition is a good fix, but I should update to a simpler example anyways.

**Comment by salper** [comment]
Arf, I could actually have made it point free:
```javascript
const concatMap = liftA2(concat);
```
What do you mean by simpler ?

**Comment by DrBoolean** [comment]
Instead of `liftA2(liftA2(concat))` I should do:

`var CTM = Compose.of(Task.of(Maybe.of(x)))`
where
`Compose.prototype.map = curry((f, x) => map(map(f), x))`

Well...on second thought. Maybe I'll just sneak in the extra `liftA2`
