### ISSUE TITLE
Free can openers

### ISSUE THREAD

**Issue by onmyway133** [MostlyAdequate/mostly-adequate-guide#168]
Hi, I'm reading [Free can openers](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch10.html)

## `map` is defined using `ap`
> I mentioned earlier that of/ap is equivalent to map. We can use this knowledge to define map for free:

```
// map derived from of/ap
X.prototype.map = function(f) {
  return this.constructor.of(f).ap(this);
}
```

But `ap` is defined using `map`, so is there a cycle here?

> We can define ap like so:

```
Container.prototype.ap = function(other_container) {
  return other_container.map(this.__value);
}
```

## `map` is defined using `chain`
> Monads are at the top of the food chain, so to speak, so if we have chain, we get functor and applicative for free:

```
// map derived from chain
X.prototype.map = function(f) {
  var m = this;
  return m.chain(function(a) {
    return m.constructor.of(f(a));
  });
}
```

But in [Chapter 9](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch9.html), `chain` is defined using `map` and `join`, so is there a cycle here?

```
//  chain :: Monad m => (a -> m b) -> m a -> m b
var chain = curry(function(f, m){
  return m.map(f).join(); // or compose(join, map(f))(m)
});
```

**Comment by zerkms** [comment]
> But ap is defined using map, so is there a cycle here?

It's actually frequent to provide generic "cycled" implementations for base types and demand a user to provide a particular implementations for specific types.

In this case I'm sure it was just an example that it might be implemented with that.

**Comment by DrBoolean** [comment]
Yep! It is necessary to define one or the other manually, but then you get it for free.

**Comment by onmyway133** [comment]
@zerkms @DrBoolean thanks, I think we should state "minimal complete definition" in the book
