### ISSUE TITLE
Ch8 - code sample not showing

### ISSUE THREAD

**Issue by wmonk** [MostlyAdequate/mostly-adequate-guide#170]
I've downloaded the epub from gitbooks and have opened in iBooks. I've attached a screenshot to show how the code sample isn't showing in the application. I can't think of a reason why, but you guys might know better.

Thanks BTW, the book is awesome!

![screen shot 2015-09-14 at 17 13 21](https://cloud.githubusercontent.com/assets/175278/9855137/5cf3fa82-5b04-11e5-9b3e-40368e37007e.png)

**Comment by DrBoolean** [comment]
Weird! I'm having a few epub issues...I'm honestly not sure what to do about them yet, but I'll research.

**Comment by KtorZ** [comment]
Probably linked to #186
