### ISSUE TITLE
Instructions in applicative_exercises.js Maybe slightly misleading

### ISSUE THREAD

**Issue by ajgreenb** [MostlyAdequate/mostly-adequate-guide#174]
Specifically, Exercise 2 is meant to be a rewrite of Exercise 1, but in your answer and in the spec, they have different type signatures:

```haskell
ex1 :: Number -> Number -> Maybe Number
ex2 :: Maybe Number -> Maybe Number -> Maybe Number
```

Perhaps it could be clarified by adding type signatures or modifying the spec/answer?

**Comment by ajgreenb** [comment]
Not a huge issue, but my first implementation

```js
var ex2 = function (x, y) {
  return liftA2(_.add, Maybe.of(x), Maybe.of(y));
}
```

wasn't passing, which tripped me up until I realized that `x` and `y` were being passed pre-lifted.

**Comment by DrBoolean** [comment]
Thanks! That's a really good call. I'll update.
