### ISSUE TITLE
EPUB max font size too small

### ISSUE THREAD

**Issue by eduedix** [MostlyAdequate/mostly-adequate-guide#175]
I am  reading  this excellent book on an ipad mini 2 using ibooks app. The maximum settable font size is still too small to read. Can you fix this issue?

**Comment by DrBoolean** [comment]
I'm not sure. I think we have to contact gitbook for that.

**Comment by eduedix** [comment]
https://github.com/GitbookIO/gitbook/issues/989#issuecomment-151459977

you might find this interesting.
