### ISSUE TITLE
Please use Simplified English

### ISSUE THREAD

**Issue by yassermzh** [MostlyAdequate/mostly-adequate-guide#176]
Although it makes the text much more enjoyable, it also makes it hard to understand for non-native speakers. For example, for me the following is like reading Shakespeare:

> Mapping over our IO has built up a mighty impure computation and running it is surely going to disturb the peace. So where and when can we pull the trigger? Is it even possible to run our IO and still wear white at our wedding? The answer is yes, if we put the onus on the calling code. Our pure code, despite the nefarious plotting and scheming, maintains its innocence and it's the caller who gets burdened with the responsibility of actually running the effects. 

It's just a suggestion to make it more available to more readers. I enjoyed the text. It's great.

**Comment by TrevorBasinger** [comment]
Honestly, I don't think it should change. It is what sets this particular book apart from the others. I'm not trying to be insensitive to other people who have trouble understanding, but the author clearly enjoys writing in this style and it is this same style that helps make functional programming less ominous. The point of this book is to make functional programming more approachable by way of expressive language. There are many other books that explain functional concepts just as well in a more concise/to-the-point way.

**Comment by guumaster** [comment]
There are several translation efforts going on to make it more accessible to a broader audience. I don't think changing the style of writing would help here.

**Comment by yassermzh** [comment]
Maybe I did it wrong. I didn't ask for any changes in current text. Sure it's great and enjoyable, I can feel it if not understand it completely. I just wanted to provide feedback to the author that his style is a bit hard for some for his future writings! I just didn't know where to comment on this.

**Comment by spasiu** [comment]
One of the reasons I love reading this book is that the flowery prose make it much more engaging to read. I wouldn't learn as much if it were written with another style. PS, I need chapter 11, stat.

**Comment by hatelove85911** [comment]
I feel the same way as yassermzh. Maybe there should be a version for plain english. I'm not a native speaker. Sometimes I can't understand the meaning of some of phrases or sentences and I'll have some worry: should I continue reading? Am I missing important information here?

**Comment by zerkms** [comment]
@hatelove85911 the only way to grow - is to put a bar higher than you can handle at the moment.

PS: a non-native speaker here, for sure.

**Comment by gabrielflorit** [comment]
The writing style is fantastic! Don't change a thing.
