### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by VictorGa** [MostlyAdequate/mostly-adequate-guide#185]
@DrBoolean I love the book! I've read that @guumaster is going to work on spanish translations. 
I couldn't see any list of who is doing which translations.
Is there a need for spanish translator or supporting @guumaster?
I'm more than happy to help!

**Comment by EdgarOrtegaRamirez** [comment]
So do I. :smile:

**Comment by DrBoolean** [comment]
Hi @VictorGa

So far https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/TRANSLATIONS.md is the place to look. I'm not sure what's up with spanish, but I can say I'm all for it :)

Maybe we should wait to hear from @guumaster to see if that work was started or planned.

**Comment by guumaster** [comment]
Quoting myself: 
>  I'm up to collaborate on maintenance and also with the spanish translation.

I volunteered to collaborate with the organization tasks, and help manage the hassle of coordinate the different teams and repos. And if anyone starts a spanish translation, I could also participate.

I do have a fork, that I just renamed to "-es", @DrBoolean, please, could you create a new ES team and add the three of us to the org? Then I could transfer the repo and we can start the translation there.

**Comment by VictorGa** [comment]
@guumaster sounds good  :+1:

**Comment by paparga** [comment]
@guumaster I'm in!

**Comment by DrBoolean** [comment]
Done!

**Comment by guumaster** [comment]
I cannot transfer the repo without admin rights. Could you give those temporally until the transfer is done? Thanks!

**Comment by DrBoolean** [comment]
sure!

**Comment by guumaster** [comment]
Cool!, lets the translations begin! :laughing:
