### ISSUE TITLE
enhancement - links to actual codebases using this style

### ISSUE THREAD

**Issue by bgvianyc** [MostlyAdequate/mostly-adequate-guide#192]
Given how unique this functional style is in the world of javascript, it would be helpful if there was some links to open source projects using functional javascript so as so see how it's implemented in real world examples.

**Comment by Bondifrench** [comment]
Check my examples in codepen, the exact replication of the example application from [Chapter 6](http://codepen.io/bondifrench/pen/KdLNaV) and a slightly more elaborate one [here](http://codepen.io/bondifrench/pen/NGmXKB)
