### ISSUE TITLE
Impure vs Pure chapter3

### ISSUE THREAD

**Issue by jmilkiewicz** [MostlyAdequate/mostly-adequate-guide#193]
Hi

Within Portable / Self-Documenting section an example of pure and impure functions are provided (both named signUp). 
The reasoning is that "pure" function explicitly takes parameters (Email, DB, attrs) which are then used within a function body and "impure" version does not. Nevertheless a body of "impure" function does not use any parameter (neither Email nor DB) except for `attrs` which is passed in as function parameter. Based on that i still consider "impure" version impure  ? If yes, then what does make it impure? Is it usage of `welcome` and/or  `saveUser` which are defined outside of `signup` function (where `signup` has no control over) ?

**Comment by Pamplemousse** [comment]
Hello @jmilkiewicz

What is implied by the example is that implementations of "saveUser" and "welcomeUser" are dependent on some external components (Db, Email).

In the case of the the impure function, these dependencies are not injected, which means that you rely on the context in which you are calling "saveUser" and "welcomeUser" to provide the "Db" and "Email" that are required in their respective implementations.

On the other hand, with a pure function, the context does not matter as long as you provide all dependencies to the functions as parameters.

**Comment by jmilkiewicz** [comment]
Hi. 

My point is that the sample code of impure version shall be:

```javascript
var signUp = function(attrs) {
  var user = saveUser(DB, attrs);
  welcomeUser(Email, user);
};
```
instead of 
```javascript
var signUp = function(attrs) {
  var user = saveUser(attrs);
  welcomeUser(user);
};
```
to emphasize that both calls to saveUser and welcomeUser require some dependencies (DB and Email). Since none of dependencies is provide/injected they would be resolved from calling context (which can not be controlled by "signup" function )

**Comment by DrBoolean** [comment]
You are right about the reason for it's impurity being a bit ambiguous. You are also right in your assumption that it is environmental dependencies that make it such.

In the example, I was kind of intending all three functions to be tangled in the environmental web, but there is no text to support that. Your code is a good solution to demonstrate that `signUp` is impure though it doesn't pack the punch I was hoping for with hidden global dependencies.

I'm debating whether it's better to point out that the Db connection and Email client are accessed willy nilly or update the code to what you have.

I'm for whatever is easier to understand without thinking too hard. Any thoughts?

**Comment by jmilkiewicz** [comment]
Maybe you can split it into 2 examples: 
a) just like I presented - a function that depends on environmental dependencies  is impure,
b) I would assume that a function that depends(calls) an "impure" function becomes impure as well. So if any of welcomeUser/saveUser are impure than signUp would be impure as well.

**Comment by Pamplemousse** [comment]
@jmilkiewicz, I think it is important not to mix pures and impures functions in an example.

I would tend to put some emphasis on the dependencies of the functions implementations.

What about?

```javascript
// impure
var signUp = function(attrs) {
  var user = saveUser(attrs);
  welcomeUser(user);
};

var saveUser = function(attrs) {
  // Implementation of the logic to save a User using a DB object.
}

var welcomeUser = function(attrs) {
  // Implementation of the logic to notify a User using an Email object.
}
```

**Comment by jmilkiewicz** [comment]
Hi

@Pamplemousse
This is exactly what i meant by example "b" in my previous post.  As both saveUser/welcomeUser would rely on env objects (Db, Email) so they are "impure" themselves,  than any function (like signup) which would call them is becoming "impure" as well.  

For more clarity instead of 
``` javascript 
var saveUser = function(attrs) {
  // Implementation of the logic to save a User using a DB object.
}
```
i would make some skeleton (toy) implementation, like:
``` javascript
var saveUser = function(attrs) {
   var user = DB.save(attrs);
  ....
}
```

**Comment by wcjr** [comment]
The thing that tripped me up in the pure function was the returned function.  In my mind, I would've understood the point completely if the only change had been the presence of the dependencies in the parameters, e.g.:
```
//pure
var signUp = function(Db, Email, attrs) {
    var user = saveUser(Db, attrs);
    welcomeUser(Email, user);
};
```
But the example in the book made me unsure if a pure function must always return a function.  Some clarification or an example like above might help clarify or simplify the point. 

Thanks,
Billy
