### ISSUE TITLE
Map in chapter 4. Documentation?

### ISSUE THREAD

**Issue by Moezalez** [MostlyAdequate/mostly-adequate-guide#198]
Hello there!

I really like you guide!

So I have a question. In chapter 4 you mention the method "map" as in:
"We also have the ability to transform any function that works on single elements into a function that works on arrays simply by wrapping it with map"

Where does this map come from? It's used like it is a native javascript method, but I cannot find any documentation on it.

**Comment by ChetHarrison** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map>


On Oct 27, 2015, at 3:00 AM, Moritz Sattler <notifications@github.com> wrote:

Hello there!

I really like you guide!

So I have a question. In chapter 4 you mention the method "map" as in:
"We also have the ability to transform any function that works on single elements into a function that works on arrays simply by wrapping it with map"

Where does this map come from? It's used like it is a native javascript method, but I cannot find any documentation on it.

**Comment by ChetHarrison** [comment]
Spend some time with this!

http://reactivex.io/learnrx/ <http://reactivex.io/learnrx/>


On Oct 27, 2015, at 3:00 AM, Moritz Sattler <notifications@github.com> wrote:

Hello there!

I really like you guide!

So I have a question. In chapter 4 you mention the method "map" as in:
"We also have the ability to transform any function that works on single elements into a function that works on arrays simply by wrapping it with map"

Where does this map come from? It's used like it is a native javascript method, but I cannot find any documentation on it.

**Comment by Moezalez** [comment]
But this is a method of Array, as where the map in the example seems to be a function.

**Comment by ChetHarrison** [comment]
I believe Brian is referring to the Ramda implementation of map. But it is fairly trivial to roll your own. Check out the tutorial link I just sent you. You will see what I am talking about.

On Oct 27, 2015, at 8:24 AM, Moritz Sattler <notifications@github.com> wrote:

But this is a method of Array, as where the map in the example seems to be a function.

**Comment by DrakeLeung** [comment]
I think it's a **native JavaScript  method with currying**, check out [support.js](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code%2Fpart1_exercises%2Fsupport.js) :)

**Comment by mallowigi** [comment]
This is part of one of his libraries

**Comment by Moezalez** [comment]
I feel like this should be a little more clear
