### ISSUE TITLE
indicating "parts"

### ISSUE THREAD

**Issue by wulfmeister** [MostlyAdequate/mostly-adequate-guide#200]
As far as I can tell, there is no indication of which of the three "parts" the reader is in.  It's also not indicated in the gitbook.  Is this something that only exists in the readme to describe the scope of the book?  If not, it might be helpful to indicate which part the reader is in at the head of each chapter.

**Comment by DrBoolean** [comment]
Hi @wulfmeister 

I actually used to have parts and chapters underneath, however, gitbook didn't like that format so I got rid of them. I've got to think of another way to do that. It switches from Pt1 to Pt2 in chapter 8, but you're right, there's no way to know that at the moment.

**Comment by wulfmeister** [comment]
That makes sense.  I've made a PR that edits the readme to reflect that.
