### ISSUE TITLE
Why use constructors in chapter 8?

### ISSUE THREAD

**Issue by meChrisReed** [MostlyAdequate/mostly-adequate-guide#202]
In chapter 8 the keywords "this" and "new" are used unnecessarily.

This could easily be replaced with 
``` javascript
var container = function (x) {
  function logValue () {
    console.log(x);
    return x;
  }
  
  function map (f) {
    return identity( f(x) );
  }

  return {
    logValue: logValue,
    map: map
  };
};

var maybe = function (x) {
  function isNothing () {
    return (x === null || x === undefined);
  }
  
  function map (f) {
    return isNothing() ? maybe(null) : maybe( f(x) );
  }
  
  return Object.assign(
    container(x), {
    isNothing: isNothing,
    map: map
  });
}
```

I am new to functional programming in general. Please let me know if there is a reason for using "this" and "new" or if it is just a style thing. I did the "this" free style when I was trying the examples and it worked just fine.

A practical benefit of this approach is that "x" or "value" are actually inaccessible. Unless you provide an interface method for it.

also the ".of()" syntax seems unnecessary. That could just be a lack of understanding on my part.

I could make the change if this is an acceptable idea.

**Comment by DrBoolean** [comment]
Hi! I just saw this issue. I'm a big fan of the closure based object in JS and have an eternal disdain for `this`.

The reason for `new` is primarily to leave objects open to extension. It's how all the popular libraries work so I went with the flow. I dig your implementation though.

`of` is more than a replacement for `new`, but I don't touch on that until Ch9.

**Comment by meChrisReed** [comment]
Thanks for the feedback. I completely understand the decision to go with what frameworks are doing. Right now I am working on a this free pattern for React.

**Comment by meChrisReed** [comment]
Is there any way to close this issue?
