### ISSUE TITLE
Applicatives, Data.Task and Parallelism

### ISSUE THREAD

**Issue by rjmk** [MostlyAdequate/mostly-adequate-guide#205]
Hi all,

When looking through the Data.Task library, I couldn't work out how, for example, fetch requests could be running in parallel. And, indeed, [playing around in requirebin](http://requirebin.com/?gist=b876858772abc980f443) showed that ap was not working concurrently.

I see now that the guide [does mention](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/58d382eae084c8bd2ecc10c2b6a75e604b6befe7/ch10.md#free-can-openers) that defining ap through chain (as folktale does) will miss out on concurrency. But considering that the Task datatype appears not to exist other than in folktale, I think the guide would be improved by being a little clearer / more upfront about the fact that Data.Task is not a concurrent implementation (perhaps in a footnote in 'Coordination Motivation').

Perhaps you may think it more trouble than it's worth, but I jus wanted to flag it up.

Thanks so much for the awesome guide!

**Comment by DrBoolean** [comment]
Thanks for bringing it to my attention! I think my favorite solution is to fork and fix Task :)

**Comment by paparga** [comment]
Hi @DrBoolean could you make your fork public?

Thanks!

**Comment by rjmk** [comment]
@KtorZ I'm not sure the FAQ addresses this question?

**Comment by KtorZ** [comment]
Indeed, not directly. The FAQ aims at cleaning a bit issues that are no longer ongoing. 
I judged this one outdated and not relevant as it relates more to the Folktale library than to the book itself. 

Plus, if you take a look at the question: `What is Either? What is Future? What is Task?`
It stands partially for that issue. We're likely to create a glossary at the end to explain where all those esoteric  terms come from and how they belong to this or this library. 

I am not sure that the point about the ability of `ap` to normally run concurrently should be closely related to the fact that the `Data.Task` structure of Folktale isn't suitable for concurrent processes (even if the latter is implied by the former). Your remark is good though and I think it has been heard. 

Having said that, does it feel still irrelevant to you to have this issue closed ?

**Comment by rjmk** [comment]
I guess the reason I raised the issue on the book is because of the stated goal to make "it possible to practice and apply your acquired knowledge each day on real world programs". But also, I see the argument for closing the issue.

So, I guess I feel the commit is irrelevant to the issue, but still happy to have it closed!

**Comment by KtorZ** [comment]
And you were doing well :), that's the spirit indeed, and again, you've made a good point here. 
 
I also agree that the commit isn't the most relevant. Still, it's more of a practical issue here (it took already time to go over each of those issues, I just ended up by closing those which deserve to be closed at once).
