### ISSUE TITLE
Incorrect comment on Functor Exercise 1

### ISSUE THREAD

**Issue by referentiallytransparent** [MostlyAdequate/mostly-adequate-guide#210]
The comment does not express the correct intention of the exercise
`// Use _.add(x,y) and map(f,x) to make a function that increments a value inside a functor`

This should be
`// Use _.add(x,y) and map(f,x) to make a function that increments a value inside a functor by 1. For example if Identity(1) then ex1(Identity(1)) is Identity(2)`

**Comment by gyzerok** [comment]
Word "increment" already mean "by 1"
01.12.2015 8:30 пользователь "Calvin Lee" <notifications@github.com>
написал:

**Comment by referentiallytransparent** [comment]
I would have to disagree on that. According to the dictionary:

in·cre·ment
noun
1. an increase or addition, especially one of a series on a fixed scale.

2. cause a discrete increase in (a numerical quantity).

These definitions show that increment corresponds to a +X increase where X is any positive number and not directly implied to be 1

**Comment by kad3nce** [comment]
@referentiallytransparent, you may be correct in the context of the English language, but in my experience, in the context of JavaScript (really programming in general) **increment** implies "by one".

See [MDN on JavaScript's Increment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Increment_()) for an example.

**Comment by referentiallytransparent** [comment]
Okay, I'm fine with that. It's clear after reading the test.
