### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by eliagentili** [MostlyAdequate/mostly-adequate-guide#216]
Hi,
i've started the Italian translation, can i enjoy the organization?
Here's my repo:
https://github.com/eliagentili/mostly-adequate-guide

Thank You

**Comment by DrBoolean** [comment]
OMG AWESOME!

**Comment by eliagentili** [comment]
I've some problems transferring the repo.
May need to create a new repo?

**Comment by KtorZ** [comment]
Indeed. You won't be able to have both the fork and the original repo under the same organization.
