### ISSUE TITLE
Trying to understand the concept of monad

### ISSUE THREAD

**Issue by geohuz** [MostlyAdequate/mostly-adequate-guide#219]
Start from Ch8 I feel myself was trapped into a myth on the rational of the Maybe, then I found this article which is a better explanation for the concept: http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html#translations

**Comment by huangp** [comment]
Just want to say thank you

**Comment by DrBoolean** [comment]
great great great article
