### ISSUE TITLE
Where is Chapter 11?

### ISSUE THREAD

**Issue by huangp** [MostlyAdequate/mostly-adequate-guide#221]
Firstly excellent book.

Sorry if I miss anything in the book but I can't find chapter 11. Nor does things mentioned in part 3. Is this book still in progress? If yes maybe mention it in README

**Comment by KtorZ** [comment]
The book is indeed still in progress. I find it pretty clear so far but meh :| 
A tiny PR to mention that would be appreciated.

**Comment by gabrielflorit** [comment]
I believe you meant to say this book is AMAZING.

**Comment by huangp** [comment]
It is indeed AMAZING :+1:  Best book I came across so far.
