### ISSUE TITLE
usage of composition law appeared in example code before it is introduced in ch.8

### ISSUE THREAD

**Issue by geohuz** [MostlyAdequate/mostly-adequate-guide#222]
The composition law is introduced in "A spot of Theory", 

```
// composition
compose(map(f), map(g)) === map(compose(f, g));”
```

But we can see the application in the earlier code, like:

```
//  getConfig :: Filename -> Task Error (Either Error (IO DbConnection))
var getConfig = compose(map(compose(connectDb, JSON.parse)), readFile);
```

and 

```
//  findParam :: String -> IO Maybe [String]
var findParam = function(key) {
  return map(compose(Maybe.of, filter(compose(eq(key), head)), params), url);
};
```

that will confuse the new practiser, I'm not sure if the author intend to write in this way

**Comment by KtorZ** [comment]
The composition function is introduced in chapter 5, in the very first lines *"Here's compose: "*.
The part of the 8th chapter to which  you refer is about functors and how functors satisfy some laws. One of them is the composition **law** which is mathematically defined thanks to the composition (or circle) **operator** or in our case, the `compose()` **function**. 

Thus, nothing is wrong here, the `compose()` function has been introduced before, and some laws are given once functors have been introduced as well :)
Try to read again chapter 5 maybe if your insights aren't clear :/

**Comment by geohuz** [comment]
Ok, I found the specific law of equation at the ch.6, "A Principled Refactor", 

```
// map's composition law
var law = compose(map(f), map(g)) == map(compose(f, g));
```

I should think about applying the law to the functor too, may be my mind twisted too much along the way. I'm not saying there is anything wrong, I just can't figure out the reason of the code some times. :-)
