### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by fonzerelly** [MostlyAdequate/mostly-adequate-guide#233]
Hi Brian I started to work an a german translation of your magnificant book (https://github.com/fonzerelly/mostly-adequate-guide). May I join your organization?  Is there already somebody else working on a german version?

Thanks.
Chris

**Comment by KtorZ** [comment]
Nice :+1: 
You should have received an invitation :)

**Comment by DrBoolean** [comment]
Yey! Thanks for handling that @KtorZ

**Comment by Maccodonaldo** [comment]
Hi, 
Is/was there a reason the work on the german translation was discontinued ? 
Daniel
