### ISSUE TITLE
If I want to use Maybe, Either, IO., etc  - Is there a library I should get, or should I be creating my own Functors?

### ISSUE THREAD

**Issue by samspot** [MostlyAdequate/mostly-adequate-guide#238]
For example, in the book you say the implementation of Maybe is simplified.  Do most people roll their own Functors, or are there some suggested libraries?  I kept expecting a recommendation as I read the book, but haven't seen anything yet.

**Comment by KtorZ** [comment]
You can have a look at http://folktalejs.org/ (mentioned in the book when talking about Tasks and Futures) 
:)

**Comment by samspot** [comment]
Thanks!  Looks really great!
