### ISSUE TITLE
Why not a chapter on 'Tuples' ?

### ISSUE THREAD

**Issue by bySabi** [MostlyAdequate/mostly-adequate-guide#239]
Hi @DrBoolean thanks for this wonderful book. All JS community owe you.
I´m a functional incomer, not soo newbie thanks to this book. :-)
I wonder why is not a `Tuple` chapter.  You not have time to write it?  or  just is not make sence on JS or is not needed ?

EDIT: And I forget it!. I miss a more deepest words about `fantasy-land` algebraic structures: Setoid, Semigroup, ... To close this book on a high note.

**Comment by DrBoolean** [comment]
Tuples are very useful! I would have added them in the ch8-10 examples, but there are so many types that I'd never get to them all. Tuples are in ramda-fantasy as well as the fantasyland repos and implement the full functor/monad spec.
