### ISSUE TITLE
curry in chapter4 is not well explained 

### ISSUE THREAD

**Issue by musikele** [MostlyAdequate/mostly-adequate-guide#241]
I had to read this chapter three to four times to understand the concept of curry. Of course it is very interesting. 

However I believe that some explanation about curry should be given. For example some details of its "magic". 

I have also done an experiment of writing "match" without curry, and I got the exeption ... maybe writing the errror would be clearer.

Also, it would be very appreciated if you write what the example functions will do, like:  "match will return a space if a space is found in str". 

That said, Keep going; I'm enjoying learning again.

**Comment by szhigunov** [comment]
@musikele there is error in example with **match** . You need replace `match(/q/i, x);` to `x.match(/q/i);`.

**Comment by kylecorbelli** [comment]
Or possibly define it as such:
```JavaScript
const { curry } = require('ramda')
const match = curry((regex, target) => target.match(regex))
```
