### ISSUE TITLE
'Read it online' is not available

### ISSUE THREAD

**Issue by FranzSkuffka** [MostlyAdequate/mostly-adequate-guide#246]
Link or source is broken.

![image](https://cloud.githubusercontent.com/assets/7485959/13176537/548cf9bc-d713-11e5-948c-8a83bc83854c.png)

**Comment by KtorZ** [comment]
Check it there: https://drboolean.gitbooks.io/mostly-adequate-guide/content/

Will be updated soon, good catch.
