### ISSUE TITLE
test case not good in this exercise?

### ISSUE THREAD

**Issue by AndyHoang** [MostlyAdequate/mostly-adequate-guide#254]
https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part2_exercises/answers/monads/monad_exercises.js#L92

I have the answer for this exercises as 
`var ex4 = _.compose(_.map(_.compose(emailBlast, addToMailingList)), validateEmail);` 
and it still pass the test.
Is it the same or just my luck?
Or I havent got monad yet?
Oh, and thanks for this very good book.

**Comment by KtorZ** [comment]
Previous exercises were a bit lenient towards the validation. This should be fixed now.
