### ISSUE TITLE
Missing variadic compose definition?

### ISSUE THREAD

**Issue by JuanCaicedo** [MostlyAdequate/mostly-adequate-guide#257]
After introducing the concept of associativity in `compose`, there's a section that discusses being able to use it to implement a variadic compose (quoted at the end of this issue). However, at that point, there has only been one definition of `compose`:

``` js
var compose = function(f, g) {
  return function(x) {
    return f(g(x));
  };
};
```

So it's not possible to run the examples shown. I think it might be worth having a definition of how to do a variadic compose, in case you're following along and typing in the code. 

I'm not sure what the best definition would be, but I'm willing to make a PR to add it in if someone else knows. My best would be maybe to change the examples above that to 

``` js
var compose3 = compose(toUpperCase, compose(head, reverse));

// or
var compose3 = compose(compose(toUpperCase, head), reverse);
```

and then do the same for `compose4`. 
## Here's the section from chapter from Chapter 5:

``` js
compose(toUpperCase, compose(head, reverse));

// or
compose(compose(toUpperCase, head), reverse);
```

>   Since it doesn't matter how we group our calls to `compose`, the result will be the same. That allows us to write a variadic compose and use it as follows:

``` js
// previously we'd have to write two composes, but since it's associative, we can give compose as many fn's as we like and let it decide how to group them.
var lastUpper = compose(toUpperCase, head, reverse);

lastUpper(['jumpkick', 'roundhouse', 'uppercut']);
//=> 'UPPERCUT'


var loudLastUpper = compose(exclaim, toUpperCase, head, reverse);

loudLastUpper(['jumpkick', 'roundhouse', 'uppercut']);
//=> 'UPPERCUT!'
```

**Comment by DrBoolean** [comment]
This is related to the lodash-fp/ramda situation where all the unqualified functions or inline definitions are confusing my use of those libraries throughout. Basically slapping a `_.` in front of `compose` (and every other function) should fix this as well as a ton of other issues. Sorry for the ambiguity.

**Comment by JuanCaicedo** [comment]
Ah okay, do you want me to make a PR with `compose -> _.compose` for this code example?

**Comment by DrBoolean** [comment]
Sure!

**Comment by JuanCaicedo** [comment]
Cool, I have a couple questions about the scope:
- Should all code snippets after the lodash-fp/ramda is introduced use `_.compose`?
- Same for other `_` functions, like `_.map`, `_.split`, `_.replace`?
- Should this be applied to other chapters? My idea would be to keep the example implementation and  shortly after explain that the libraries provide those methods and that's what will be used going forward. An example of this is `map` in chap4. 
  * A benefit of this is that you could copy paste examples more easily. Currently if I see `map` in chapter 5, I have to flip back to chapter 4 and copy the implementation. I would have to do that with `_.map`

**Comment by mishaszu** [comment]
I have had the same problem! This example is very misleading. While you create compose function with 2 params, it will ignore all extra params. So example with 3 functions as parameters won't work as you wish.
You did not give any change of composite function, here is something more, you told to read params functions from right to left, and there is no explanation why. Is it from lodash or ramda?

I make investigation how to implement the easiest compose in javascript:
```
function compose() {
    var args = arguments
    return function(x) {
        var i, max = args.length
        for(i = 0; i < max; i++){
            x = args[i](x)
        }
        return x
    }
}
```
There is nothing from right to left, in this case it works from left to right.

One more thing is, how can you make examples with external libraries? There is no prove (in book) if libraries's methods are pure functional programming, and if you write functional code using not functional methods it's not pure FP.

So...
It's really confusing, should we use extra libraries to make this example works, should we believe if lodash is based on FP, and why we need lodash (or anything else) at all for such a simply example.

**Comment by KtorZ** [comment]
Fixed with the restructuring and introduction of the appendixes :+1:
