### ISSUE TITLE
Epub validation errors

### ISSUE THREAD

**Issue by colepeters** [MostlyAdequate/mostly-adequate-guide#262]
I’ve noticed that there are several validation errors on the current .epub version of the book, which is preventing me from uploading it to the services I use for storing my ebooks. I’m not familiar with fixing epub errors, but for reference I’ve attached the validation output from [IDPF’s EPUB Validator](http://validator.idpf.org/).

Any chance these could be looked at and fixed?
Thanks for all the work on this book!

[EPUB Validator (beta) Results.pdf](https://github.com/MostlyAdequate/mostly-adequate-guide/files/196107/EPUB.Validator.beta.Results.pdf)

**Comment by tnguyen14** [comment]
This is similar to #186?

**Comment by KtorZ** [comment]
I'll close in favor of #186 to clean up a bit the issue list.
