### ISSUE TITLE
Correction for Chapter 10: Bro, do you even Lift ? undefined user

### ISSUE THREAD

**Issue by thurt** [MostlyAdequate/mostly-adequate-guide#271]
`user` appears to be an unknown variable ?

``` javascript
// checkEmail :: User -> Either String Email
// checkName :: User -> Either String String

//  createUser :: Email -> String -> IO User
var createUser = curry(function(email, name) { /* creating... */ });

Either.of(createUser).ap(checkEmail(user)).ap(checkName(user));
// Left("invalid email")

liftA2(createUser, checkEmail(user), checkName(user));
// Left("invalid email")
```

I think there should at least be a mock `user` variable defined, with an invalid email:

``` javascript
var user = {
  email: "invalid_invalid",
  name: "John Doe"
}
```

**Comment by DrBoolean** [comment]
Good idea! Mind making a PR?

**Comment by thurt** [comment]
Sure I can do that. I was hesitant to make PR due to the large es6 PR, since that change could define the syntax for further corrections.

**Comment by DrBoolean** [comment]
Ahh, fair enough. Well, it's a one liner with `user` and there are already conflicts so I don't think it's too big of a deal. But yeah...

**Comment by christiantakle** [comment]
@thurt Feel free to make a PR for this, Its not a problem for me to rebase.
