### ISSUE TITLE
The ePub verison is not valide ePub 2.01

### ISSUE THREAD

**Issue by ulve** [MostlyAdequate/mostly-adequate-guide#274]
The ePub version of the book cannot be uploaded to google books. When I validated the epub file using http://validator.idpf.org/ i got the followinf errors:

| Type | File | Line | Position | Message |
| --- | --- | --- | --- | --- |
| ERROR | ch3.html | 96 | 42 | Error while parsing file 'value of attribute "id" is invalid; must be an XML name without colons'. |
| ERROR | ch3.html | 103 | 68 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch3.html | 105 | 76 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch3.html | 111 | 64 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch5.html | 166 | 65 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch5.html | 183 | 64 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch5.html | 184 | 44 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch6.html | 117 | 65 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch6.html | 147 | 62 | Error while parsing file 'element "img" missing required attribute "alt"'. |
| ERROR | ch10.html | 240 | 85 | Referenced resource could not be found in the EPUB. |
| ERROR | ch4.html | 122 | 370 | Reference to non-standard resource type found. |
| ERROR | ch4.html | 122 | 370 | Found a reference to a resource that is not a spine item. |
| ERROR | index.html | 21 | 104 | Referenced resource could not be found in the EPUB. |
| ERROR | index.html | 58 | 92 | Referenced resource could not be found in the EPUB. |
| ERROR | index.html | 60 | 97 | Reference to non-standard resource type found. |
| ERROR | index.html | 60 | 97 | Found a reference to a resource that is not a spine item. |
| ERROR | index.html | 62 | 97 | Reference to non-standard resource type found. |
| ERROR | index.html | 62 | 97 | Found a reference to a resource that is not a spine item. |
| ERROR | index.html | 64 | 88 | Reference to non-standard resource type found. |
| ERROR | index.html | 64 | 88 | Found a reference to a resource that is not a spine item. |

**Comment by Delapouite** [comment]
This pull request should fix the errors related to missing alt attributes : https://github.com/MostlyAdequate/mostly-adequate-guide/pull/275

On a side note, a similar issue was already open : https://github.com/MostlyAdequate/mostly-adequate-guide/issues/262

This one has a full listing a stuff to fix which is handy thanks @ulve

**Comment by tnguyen14** [comment]
This was previously reported at #186

**Comment by KtorZ** [comment]
closing in favor of #186
