### ISSUE TITLE
Question on Chapter 10: Defining ap via chain will miss the optimization of running things concurrently?

### ISSUE THREAD

**Issue by kpaxqin** [MostlyAdequate/mostly-adequate-guide#286]
From the Chapter 10: 
>It should be pointed out that part of ap's appeal is the ability to run things concurrently so defining it via chain is missing out on that optimization.

But since the `ap` is used in the way like 

`Either.of(createUser).ap(checkEmail(user)).ap(checkName(user));`

`checkEmail` and `checkName` will run immediately when they been called, and we run both of them at the same time (almost) by calling them and pass the result to `ap`

Here I just write some code with Promise to show this case 

```js
Promise.prototype.ap = function (other) {
  return this.then(function(f) {
    return other.then(f)
  })
}

getP = function(n) {
  return new Promise(function(res, rej){
    setTimeout(function(){
      console.log(n);
      res(n)
    }, 3000)
  })
}

//curried add function
function add(a) {
  return function(b) {
    var result = a + b;
    console.log('result: ' + result);
    return result;
  }
}

Promise.resolve(add).ap(getP(1)).ap(getP(2))

/* 
following things will be shown in 3 seconds : 
> 1
> 2
> result: 3
*/
```

You can run it in the console panel of your browser. And we will see the result in 3 seconds later, not 6.

It seems we still got the ability of running things concurrently, or do I miss understood something?

**Comment by safareli** [comment]
Promise starts execution when they are created(have side effect) so if you run this:
```
var a = new Promise(function(res, rej){
  console.log(1)
  setTimeout(function(){
    console.log(3);
  }, 3000)
})
console.log(2);
```

in console you would see `1`, `2` and after 3000ms `3`.

You could check [data.task](https://github.com/folktale/data.task) it's like a lazy promise.
It starts executing when you call `run()` on it so when you create new Task it does not have side effects.
```
var a = new Task(function(rej,res){
  console.log(2)
  setTimeout(function(){
    console.log(3);
    res(4)
  }, 3000)
})
console.log(1);
a.run(function onReject(){}, function onSuccess(n){
  console.log(n)
})
```
In console you would see `1`, `2` and after 3000ms `3`, `4`.

Now with `data.Task` if you implement `ap` using `chain` it would be sequential, once it was an issue with `data.task` but got [fixed](https://github.com/folktale/data.task/pull/33/files)

**Comment by kpaxqin** [comment]
@safareli 
Thanks for your reply, really clear! 
I've heard data.task before, but haven't think about how the lazy behaviour makes it sequential in this case.

**Comment by safareli** [comment]
Welcome!
