### ISSUE TITLE
Ch 5 'reduce' is unexplained

### ISSUE THREAD

**Issue by rapPayne** [MostlyAdequate/mostly-adequate-guide#290]
On the lines which read:

``` js
var reverse = reduce(function(acc, x) {
  return [x].concat(acc);
}, []);
```

The reduce function is a mystery.  I'm guessing it comes from a library?

We should either explain where it came from, giving reference to documentation for that library or preferably, refactor the example to use ES2015's Array.prototype.reduce() method.

**Comment by rajasegar-c** [comment]
@rapPayne 
Actually the definition of reduce is given in Chapter 7 and it is coming from lodash
the definition goes like this:

```javascript
var curry = require('lodash/curry');

//  reduce :: (b -> a -> b) -> b -> [a] -> b
var reduce = curry(function(f, x, xs) {
  return xs.reduce(f, x);
});
```

Hope it helps...

**Comment by ahlusar1989** [comment]
@rapPayne If you come from a functional programming background, this article (citing a Scala and Spark - specific heuristic) explains very well the reduce operation: http://stackoverflow.com/questions/25158780/difference-between-reduce-and-foldleft-fold-in-functional-programming-particula

**Comment by ferdaber** [comment]
@rajasegar-c wouldn't the type signature for reduce be:

```js
// reduce :: ((b, a) -> b) -> b -> [a] -> b
var reduce = curry(function(f, x, xs) {
  return xs.reduce(f, x);
});
```
if we're using the plain JS `Array.prototype.reduce` function?
