### ISSUE TITLE
Creating private variables for module

### ISSUE THREAD

**Issue by partially-applied** [MostlyAdequate/mostly-adequate-guide#292]
I am trying to structure an application with some of the ideas presented in this book. However it is farily difficult to get your head around how to structure traditional apps using some of the techniques. 

A simple example would be structuring canvas based api. 

lets define main

```livescript

main = (initial-state) !->


    keys = Object.keys initial-state # get all keys 

    for I in keys 
        @[I] = initial-state[I]

    @textAlign = "center" # some defaults



main.of = (args) ->  new main args  # based on what Dr Boolean Suggested

```

So far so good - I then went on to define some other methods

```livescript
main.prototype.add = (points) ->

   # some code that mutates canvas and points data

```

### Problem 1

I suddenly realized I was unable to define private methods

### Problem 2

Does it even make sense to structure a canvas based problem using ideas presented in this book ?

**Comment by dtipson** [comment]
What is main meant to be here?  It doesn't look like a specific container type, so why does it have an `of` method? If you're building something that deals with modifying state over consecutive operations, check this video out: https://vimeo.com/109984691 for a sense of how it can work.

There are also patterns in Haskell I've come across for how to deal with canvas (namely, as a remote interface http://ku-fpg.github.io/practice/remotemonad/) that might be worth checking out, all of which dal with IO (which is what canvas operations are probably going to need to be treated as).

**Comment by partially-applied** [comment]
I get the feeling I am thinking about the issue in the wrong way - private state and variables are bad design patterns in functional programming :(

**Comment by safareli** [comment]
for `structure traditional apps` i think you should check this [links](https://gist.github.com/safareli/c3b91792dfa1ce4a86aacb75f91cea0a) especialy Elm and Cycle.js ones
