### ISSUE TITLE
Question on exercize 5 for functors

### ISSUE THREAD

**Issue by blocka** [MostlyAdequate/mostly-adequate-guide#296]
The solution is 
```
var upperTitle = _.compose(_.toUpper, _.prop('title'));
var ex5 = _.compose(_.map(upperTitle), getPost);
```

If I understood everything until now, this can be improved by using the `safeProp` function instead.

` _.compose(_.toUpper, safeProp('title'));`

Since `safeProp` returns a `Maybe` we need to add `_.map`

` _.compose(_.map(_.toUpper), safeProp('title'));`

But when I do that, I get `Maybe("LOVE THEM FUTURES")` instead of `"LOVE THEM FUTURES".

There's obviously one salient point I missed here....

**Comment by safareli** [comment]
`_.map(_.toUpper)`
1. takes value from Maybe
2. applies `_.toUpper`
3. wraps result of 2. in Maybe

So after map you should get value in maybe(as you are getting) not just a value.

**Comment by blocka** [comment]
I'm not asking for an understanding of what is happening here. I'm asking how to use `safeProp` instead of `_.prop`

So that 
```
E.ex5(13).fork(console.log, function(res){
      assert.deepEqual(res, 'LOVE THEM FUTURES');
      done();
    })
```

will work correctly

**Comment by KtorZ** [comment]
To understand how to use `safeProp`, you better understand what is happening here. The explanation of @safareli tells you everything you need to know. 

Your end-value is "wrapped" in a `Maybe`. Should you want to display your text, you should refer to the *api* of your `Maybe` implementation (could it be from the language or from a library). If we stick to the book, using the `maybe` function from the chapter 8 will do.

```js
//  maybe :: b -> (a -> b) -> Maybe a -> b
var maybe = curry(function(x, f, m) {
  return m.isNothing() ? x : f(m.__value);
});
```

Therefore, by providing a default value (in case there's `Nothing` and not `Just something`), you can extract the content from the `Maybe` functor.
