### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by amilajack** [MostlyAdequate/mostly-adequate-guide#299]
The examples should be updated to use ES6/7. Especially `const` and the spread operators.

**Comment by KtorZ** [comment]
.... no?

There are already some discussions about which direction the book should be taking. ES6 is nice, and book examples and exercises have already been translated in a dedicated ES6 version (see #273)

For the current version of the book, it makes more sense to stick with the ES5 implementation as it was the original one.
