### ISSUE TITLE
PR Proposal: ESLint support for .md files?

### ISSUE THREAD

**Issue by amilajack** [MostlyAdequate/mostly-adequate-guide#300]
@DrBoolean It is possible to lint the markdown files using eslint and a markdown parser. Would a PR for this be welcome?

**Comment by DrBoolean** [comment]
That's pretty rad, but i'm not sure linting is going to be a huge win at this point. I should have done that from day 1. The loose style might lend itself to teaching better anyhow. Thanks for the thought though!
