### ISSUE TITLE
Request: Lenses, Prisms, and Traverals

### ISSUE THREAD

**Issue by ccorcos** [MostlyAdequate/mostly-adequate-guide#304]
I have a good grasp on lenses -- but I have absolutely no idea what a prism or a traversal is. I ran into this issue reading here: http://blog.functorial.com/posts/2015-11-20-Thermite.html

I'd love to see some more chapters! 👍 👍 👍

**Comment by DrBoolean** [comment]
A prism is just a lens for a Sum type (e.g. a lens with a notion of failure). Traversals come directly from traverse, which is a chapter i hope to add soon. Thanks for the req!
