### ISSUE TITLE
Unable to run mocha

### ISSUE THREAD

**Issue by rotexhawk** [MostlyAdequate/mostly-adequate-guide#312]
If you install mochal locally and not add it manually in your path it gives you "mocha not found".  Had to change package.json and instead use npm run watch. 

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/feedback_loop.md

```
"scripts": {
    "test": "mocha exercises/**/*_spec.js",
    "watch": "npm test -- --watch"
}

npm run watch
```

**Comment by wayneseymour** [comment]
I have the same problem
