### ISSUE TITLE
When will Part 3 be published?

### ISSUE THREAD

**Issue by adispring** [MostlyAdequate/mostly-adequate-guide#313]
Hi, @DrBoolean, when will part 3 of the book be published?
I and my team have already finished reading this book, and introduce Ramda into our Project. FP and the book are great. mostly-adequate-guide is the most elegant book about FP in JavaScript I have ever read. 
We have read your plan about Part 3 of the book, it contains some advance FP concepts we want to learn.
Expect your reply :)

**Comment by kgish** [comment]
+1

**Comment by graforlock** [comment]
+1

**Comment by aitoroses** [comment]
+1

**Comment by kgish** [comment]
+1

**Comment by ahstro** [comment]
This is a duplicate of #245 :)
