### ISSUE TITLE
false positive answer in Chapter 9 ex 4?

### ISSUE THREAD

**Issue by ChenRoth** [MostlyAdequate/mostly-adequate-guide#314]
hi

I passed the ex4 spec using this answer:
`_.compose(_.map(emailBlast), _.map(addToMailingList), validateEmail)`
does it make any sense? wouldn't it mean that emailBlast actually receives `IO [Email]` instead of `[Email]`?

I think that it accidentally works because of the `.join()` invocation in `emailBlast`, which happens to coincide with IO's `join`

**Comment by nikcorg** [comment]
I came here to report the same. I was mighty confused for a while, when I compared my solution to the provided ones.

**Comment by KtorZ** [comment]
I believe this is now fixed with the latest restructuring of the exercises section :+1:
