### ISSUE TITLE
Polish translation - new contributor request

### ISSUE THREAD

**Issue by jellyfish-tom** [MostlyAdequate/mostly-adequate-guide#328]
Hello: )

am going to read and learn from the book and as there is no polish version, I thought I can try and translate. I have 5+ years in bussiness/production programming (backedn+frontend) and more than 3 in JS. Hopefully that is enough. 
Please add me to organization: )

Best, thanks for the book!
Tom

**Comment by KtorZ** [comment]
Hey, sorry for the delay. 

Is the request / wish to contribute still accurate?
