### ISSUE TITLE
Map Maybe Compose

### ISSUE THREAD

**Issue by bouzlibop** [MostlyAdequate/mostly-adequate-guide#330]
Hi. I just finished reading part of chapter 8 called [Schrödinger's Maybe](https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch8.html#schrödingers-maybe)

I found there this function:
```
//  map :: Functor f => (a -> b) -> f a -> f b
var map = curry(function(f, any_functor_at_all) {
  return any_functor_at_all.map(f);
});
```

I wanted to rewrite from dot syntax this piece of code:
```
Maybe.of({
  name: 'Dinah',
  age: 14,
}).map(_.prop('age')).map(add(10));
```

I ended up with sth like this:

```
const add10ToAge1 = compose(map(add(10)), map(prop('age')));

// Map's composition law
// const law = compose(map(f), map(g)) === map(compose(f, g));

const add10ToAge2 = map(compose(add(10), prop('age')));

add10ToAge2(
    Maybe.of({
        name: 'Dinah',
//         age: 14,
    })
);
```

And here is an issue I encountered: `add10ToAge1` and `add10ToAge2` are not equal.
One gives me `Maybe(null)` and second one gives `Maybe(NaN)`.

**Map's composition law doesn't hold here**

What are the ways of fixing it? Is there any other way (more general) than putting `Maybe.of` in `compose`?

**Comment by ferborva** [comment]
It´s odd you get this error. To start with because you end up with a Null once and a NaN a second time. I see that in your call to add10toAge2(..) you have commented out the `age` key line. This would result in the Maybe(Nan). However I don´t see why you should get a null. 

I've tried you code using ramda and data.maybe (folktale) and the results are those expected. 

Code:
```
var R = require('ramda')
var Maybe = require('data.maybe')


var map = R.curry(function(f, any_functor_at_all) {
  return any_functor_at_all.map(f);
});


const add10ToAge1 = R.compose(map(R.add(10)), map(R.prop('age')));

// Map's composition law
// const law = compose(map(f), map(g)) === map(compose(f, g));

const add10ToAge2 = map(R.compose(R.add(10), R.prop('age')));

const result1 = add10ToAge1(
    Maybe.of({
        name: 'Dinah',
        age: 14,
    })
);

const result2 = add10ToAge2(
    Maybe.of({
        name: 'Dinah',
        age: 14,
    })
);

console.log(result1)
console.log(result2)
```

Results:
```
Maybe { value: 24 }
Maybe { value: 24 }
```

**Comment by bouzlibop** [comment]
Hi @ferborva :) Thanks for reply. I commented out `age` deliberately. Just wanted to focus on _failing case_.

My point is that
`add10ToAge1` returns `Maybe { value: null }`
`add10ToAge2` returns `Maybe { value: NaN }`

And in the book the map's composition law was mentioned:

`const law = compose(map(f), map(g)) === map(compose(f, g));`

According to this law I would assume `add10ToAge1` will return same thing as `add10ToAge2`. And they don't.

**Comment by ferborva** [comment]
From the test I ran (code above) `add10ToAge1` and `add10ToAge2` do return the same result: `Maybe { value: 24 }`

Can you post you full code? Include the Maybe definition, prop, add, compose and curry functions. Difference must be in one of these

**Comment by bouzlibop** [comment]
I'm using only code from book (including Maybe implementation found in Ch.8).
As I said I'm interested in case where `age` prop is **not** found, so I removed it from the object.

Full code is here

```
var Maybe = function(x) {
  this.__value = x;
};

Maybe.of = function(x) {
  return new Maybe(x);
};

Maybe.prototype.isNothing = function() {
  return (this.__value === null || this.__value === undefined);
};

Maybe.prototype.map = function(f) {
  return this.isNothing() ? Maybe.of(null) : Maybe.of(f(this.__value));
};

var map = R.curry(function(f, any_functor_at_all) {
  return any_functor_at_all.map(f);
});

const add10ToAge1 = R.compose(map(R.add(10)), map(R.prop('age')));
const add10ToAge2 = map(R.compose(R.add(10), R.prop('age')));

const result1 = add10ToAge1(
    Maybe.of({
        name: 'Dinah',
    })
);

const result2 = add10ToAge2(
    Maybe.of({
        name: 'Dinah',
    })
);

console.log(result1)
console.log(result2)
```

add10ToAge1 returns Maybe { value: null }
add10ToAge2 returns Maybe { value: NaN }

**Comment by ferborva** [comment]
Ok. I think I found the difference. So the issue is in the how `R.add` works. Because `R.add(10, null) = 10` and `R.add(10, undefined) = NaN`. When you map each function at a time R.add is not run due to the isNothing check in the map definition (`this.isNothing() ? Maybe.of(null) : Maybe.of(f(this.__value))`). However, when you compose the functions `R.add` is run with the result of `R.prop`.

**Comment by bouzlibop** [comment]
@ferborva Yes, exactly. You are right. 

Now I wonder what are the possible, real world solutions to this problem. How to make sure **map's composition law** hold for every case.

**Comment by ferborva** [comment]
I think the law still holds. The issue here is that the Maybe map is modifying the content of the Maybe when value held is undefined. The fix could be something like this:

```
Maybe.prototype.map = function(f) {
  return this.isNothing() ? Maybe.of(this.__value) : Maybe.of(f(this.__value));
};
```

**Comment by bouzlibop** [comment]
@ferborva 🤔 seems reasonable, although I think we still have an issue. With your solution we will have:

```
Maybe {__value: undefined}
Maybe {__value: NaN}
```

Still two different ones.

**Comment by ferborva** [comment]
Ok ok ok .. I think now I understand.

So regarding the map composition law as seen in this case it won´t apply when the function mapped is run or not depending on an internal condition checked by the map function (as is the case of the Maybe).

In this particular case what I think should be done is use Maybe in a different way. The purpose of Maybe is protecting against null or undefined values. As seen, R.prop can return undefined when the key is not present. So what seems like a better solution is to do one of these:

a) Create the Maybe from the result given from your propertie search
```
Maybe.of(R.prop('age',{...}).map(....)
```

b) if you want to map a function that may return a null/undefined on the Maybe, you could chain that particular function and then continue mapping other functions (or composed functions)

```
Maybe.of({}).chain(Maybe.of(R.prop(..)).map(...)
```

**Comment by bouzlibop** [comment]
>  it won´t apply when the function mapped is run or not depending on an internal condition checked by the map function

Thanks for the explanation 😃
