### ISSUE TITLE
Pointfree snakeCase example

### ISSUE THREAD

**Issue by mjdease** [MostlyAdequate/mostly-adequate-guide#336]
```javascript
//not pointfree because we mention the data: word
var snakeCase = function(word) {
  return word.toLowerCase().replace(/\s+/ig, '_');
};

//pointfree
var snakeCase = compose(replace(/\s+/ig, '_'), toLowerCase);
```

If I'm understanding compose correctly, in the pointfree example `toLowerCase` and `replace` are functions that both accept one more argument.

In which case, this example is very confusing because the `toLowerCase` and `replace` methods used in the non-pointfree example are native string prototype methods that don't accept the string as an argument and are entirely unrelated to the functions of the same names in the pointfree example.

For `toLowerCase` specifically, I think this may just be a typo because this isn't a native function or part of Ramda as far as I can tell. Later on in this chapter for lowercasing strings the `toLower` Ramda function is used. So the change here may just be to use `toLower` and maybe reference Ramda as the source?

For `replace` specifically, as covered in #76, pointing out the source of this method would be useful with the bonus effect of making it clear that it's not the same as the `string.replace` method.

**Comment by KtorZ** [comment]
In a way, `toLowerCase` and `replace` do take a string argument. It is simply 'hidden' with the OO notation. Most representations of OO languages will actually position the target object (a.k.a `this` as the first argument to the function). Python is actually rather explicit on that point when it comes to declaring instance methods:

```py
def toLowerCase(self):
   # whatever implementation you may come up with
```

Yet, as @DrBoolean mentionned in #76, those functions refer to what's defined in the support code:

- [replace](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/support.js#L65-L67)
- [toLowerCase](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/support.js#L93-L95)

Probably worth the shot to add a small note mentioning the support code. Something like a note / hint:

> Hint: Pointfree versions of `replace` & `toLowerCase` are defined in the support code for the exercises. Do not hesitate to have a peek. 


What do you think of this?

**Comment by mjdease** [comment]
Yeah I think that would clear things up 👍

**Comment by albedoa** [comment]
I believe this is still confusing. Here is the current non-pointfree example:

```javascript
// not pointfree because we mention the data: word
const snakeCase = word => word.toLowerCase().replace(/\s+/ig, '_');
```

So we are told that the test is whether we use the data, which in this case is the string we are processing. Here is the `toLowerCase()` definition that we are encouraged to peek at:

```javascript
const toLowerCase = s => s.toLowerCase();
```

This seems to fail the same test in the same way.

**Comment by ptrfrncsmrph** [comment]
I think the distinction is that the `String.prototype.toLowerCase()` _method_ that is baked into JS cannot be used pointfree because you always have to "mention" the string you are lowercasing. For instance, if you were mapping an array of strings to that `toLowerCase()` method, you'd have to write like so:
```javascript
["FOO", "BAR"].map(s => s.toLowerCase())
```
However, in the appendix you referenced, we are using the `String.prototype.toLowerCase()` method to define a _new function_ `toLowerCase` that _can_ be used pointfree.
```javascript
const toLowerCase = s => s.toLowerCase();
```
The point isn't that the _function itself be defined in a pointfree style,_ (it's not) but that it can be used in a pointfree manner. So that first expression could now be written:
```javascript
["FOO", "BAR"].map(toLowerCase)
```
This is my understanding of what is meant by
> Pointfree versions of `replace` & `toLowerCase`

It's not that the implementations of those functions are pointfree, rather they allow us to write in a pointfree style.

**Comment by ptrfrncsmrph** [comment]
If the point of confusion is that the phrase "pointfree versions" in
> Pointfree versions of `replace` & `toLowerCase` are defined in the Appendix C - Pointfree Utilities. Do not hesitate to have a peek!

is taken to mean that the _implementations_ of those functions are pointfree? Would it be clearer if it was re-worded to something like "pointfree utility functions"? &mdash; or removed completely?

Alternatively, something could be added to the top of that appendix making it clear that the implementations of those functions are not meant to illustrate pointfree style, but that they can be _used_ in pointfree style.
