### ISSUE TITLE
Spanish translation is still working?

### ISSUE THREAD

**Issue by grunch** [MostlyAdequate/mostly-adequate-guide#346]
Hi there,

I am started reading the book in spanish and I found some things to fix, so I did a PR, I can see there is a lot of new translated chapters in PR but no merge.

The last PR (without counting mine) is from last year, can someone check those PR and aprrove it or rejecte it if their are wrong, the idea is to finish this translation.

Regards
Francisco

**Comment by KtorZ** [comment]
Hi, this issue tracker relates to the core repository. You should probably see with the Spanish repository instead, if still active.

@guumaster @EdgarOrtegaRamirez @VictorGa ?
