### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by arkadiuszizycki** [MostlyAdequate/mostly-adequate-guide#354]
Hello I would like to start translation of this book to Polish. Is it possibile?

**Comment by KtorZ** [comment]
Hi!
It is of course possible. Please follow the [guidelines about creating new translations](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/CONTRIBUTING.md#Translations). At some point, you'll have to transfer your repository to the MostlyAdequate organization and I'll invite you (and your team if any) to join and manage the Polish translation.

:+1:

**Comment by KtorZ** [comment]
Hi, @arkadiuszizycki, any updates ?

**Comment by arkadiuszizycki** [comment]
Sorry, I had a lot of personal stuff. I will start working on translation starting from July
