### ISSUE TITLE
Next Chapters (11+)

### ISSUE THREAD

**Issue by HermineF** [MostlyAdequate/mostly-adequate-guide#356]
Hi guys,

first of all thanck you very very much for all your work. I have read this book multiple times and can now enter the world of functionnal programming.
But I must say I am still hungry for new chapters... You say in chapter 10 you'll add one on for traversable/foldables but the link is not working.
Is it comming? or have you changed your plans?

Thancks for the reply,

**Comment by KtorZ** [comment]
Hi Hermine, thanks for the support! Really glad you're enjoying the book. The plan hasn't much change and the next chapters are still being worked on despite having any precise release date that I can communicate.

**Comment by KtorZ** [comment]
duplicate #245
