### ISSUE TITLE
Immutable JS's List doesn't fuse/ optimize operations? 

### ISSUE THREAD

**Issue by TomyJaya** [MostlyAdequate/mostly-adequate-guide#364]
Hi, 

Thanks for yet another good informative chapters. 

The last paragraph of "Feature Envy"  section of Ch11 (Transform Again, Naturally) says:

> Since immutable has optimized/fused operations, we can move the map(f) to the left of our natural transformation as shown in doListyThings_.

Please correct me if I'm wrong. I believe only `Seq` in `immutable` has this optimization. `List` is *not* optimized: 

```javascript
const {Seq, List} = require('immutable');

const list = List.of(1,2,3);

const finalList = list.map(x => {
    console.log("map1: " + x);
    return x + 1;
}).map(x => {
    console.log("map2: " + x);
    return x + 2;
}).filter(x => {
    console.log("filter: " + x);
    return x % 2 == 0;
})

console.log(finalList);

console.log("---- Using Seq ----");

const seq = Seq(list);

const finalSeq = seq.map(x => {
    console.log("SEQ: map1: " + x);
    return x + 1;
}).map(x => {
    console.log("SEQ: map2: " + x);
    return x + 2 ;
}).filter(x => {
    console.log("SEQ: filter: " + x);
    return x % 2 == 0;
})

console.log(finalSeq);



```

produces: 

```
map1: 1
map1: 2
map1: 3
map2: 2
map2: 3
map2: 4
filter: 4
filter: 5
filter: 6
List [ 4, 6 ]

---- Using Seq ----
SEQ: map1: 1
SEQ: map2: 2
SEQ: filter: 4
SEQ: map1: 2
SEQ: map2: 3
SEQ: filter: 5
SEQ: map1: 3
SEQ: map2: 4
SEQ: filter: 6
Seq [ 4, 6 ]

```

From the output, `Seq` operations are interleaved. Nevertheless, `List` still seems to be iterated 3 times. 

I'm using immutable version 3.8.2.

**Comment by KtorZ** [comment]
That's a good one and I believe you're right ^.^ 
Note however that the phrasing has changed a little bit recently to

[source - ch11#feature-envy](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch11.md#feature-envy)

> Also, it becomes easier to optimize / fuse operations by moving map(f) to the left of natural transformation as shown in doListyThings_.

I guess that it solves the issue in some way :)

**Comment by TomyJaya** [comment]
Cool! Thanks!
