### ISSUE TITLE
Left implementation in ch8 adds a b , but shouldn’t 

### ISSUE THREAD

**Issue by benshine** [MostlyAdequate/mostly-adequate-guide#369]
In https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch8.html#schr%C3%B6dingers-maybe

```
Left.of('rain').map(function(str) {
  return 'b' + str;
});
// Left('rain')
```

Shouldn’t this Return just `str`?

**Comment by KtorZ** [comment]
Nope ^.^
The point here is actually to show that the function provided to `map` isn't applied in case of `Left`. Passing an identity function would be cheating here for we want to see that the map didn't occur!

Cf the paragraph right below:

> Left is the teenagery sort and ignores our request to map over it. Right will work just like Container (a.k.a Identity). The power comes from the ability to embed an error message within the Left.

**Comment by benshine** [comment]
Ah, i see. It would be clearer if Left did something wacky like print “bring your umbrella because the weather calls for”...
