### ISSUE TITLE
Explanation of currying clearer if it used real chars instead of white space character class

### ISSUE THREAD

**Issue by benshine** [MostlyAdequate/mostly-adequate-guide#372]
```
match(/\s+/g, 'hello world');
// [ ' ' ]
```
In https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch4.html
Makes perfect sense if the reader understands regular expressions and that \s+ means one or more spaces.  Consider rewriting with concrete characters. 
Sometimes js programmers don’t know regexes 😱

**Comment by DrBoolean** [comment]
Good call!
