### ISSUE TITLE
Consistency in Capitalization Titles

### ISSUE THREAD

**Issue by KtorZ** [MostlyAdequate/mostly-adequate-guide#380]
Titles' capitalization is rather inconsistent throughout the book at the moment. I see two approaches for that:

- either we stick with very simple rules: First letter of the first word capitalized, as well as proper nouns. 
- or, we follow [the Chicago Manual of Style](https://en.wikibooks.org/wiki/Basic_Book_Design/Capitalizing_Words_in_Titles)

Discussion started in #379

**Comment by datenreisender** [comment]
In #380 I applied the second option. Looks ok. Mostly changes headings in the earlier chapters.

**Comment by datenreisender** [comment]
The rules behind https://en.wikibooks.org/wiki/Basic_Book_Design/Capitalizing_Words_in_Titles “are adapted from The Chicago Manual of Style”, so there are some deviations, e.g. on whether to capitalise “without”. In the CMOS it seems it should not be capitalised, so. e.g. https://headlinecapitalization.com/ and https://capitalizemytitle.com/ agree, that it should be “Can't Live If Livin' Is without You” with a lowercase “without”. I suggest, that we follow the latter style, not the one from Wikibooks.

**Comment by KtorZ** [comment]
Hmmm. I'd be curious to know the reason behind this but, fair enough :+1:

**Comment by KtorZ** [comment]
Closed with #381
