### ISSUE TITLE
Variable access?

### ISSUE THREAD

**Issue by ferborva** [MostlyAdequate/mostly-adequate-guide#382]
Hello!
I have a doubt about this chunk of code from chapter 9:

```
querySelector('input.username')
  .chain(({ value: uname }) => querySelector('input.email'))
  .chain(({ value: email }) => IO.of(`Welcome ${uname} prepare for spam at ${email}`));
```

Why is uname accessible to the last function? Wouldn't uname be limited to the scope of the first anonymous function and die with it as soon as it returns?

I tried the 'equivalent' with a Promise:

```
Promise.resolve(42)
    .then(num => `The answer is ${num}`)
    .then(msg => `${msg}. I promise, it's ${num}`)
    .then(console.log)
```

And had the console spit out 'num not defined'.
What am I missing?

**Comment by KtorZ** [comment]
Hey, good catch. I believe it's a parenthesis error that occurred with the rewrite to ES6. 

You're right about the scope and this has nothing to do with FP or monads, it's just JavaScript. I'll modify ASAP :+1:
