### ISSUE TITLE
Request add translation to Indonesia

### ISSUE THREAD

**Issue by anaufalm** [MostlyAdequate/mostly-adequate-guide#383]
Hello, I am very interested to read this project. May I translate this project into Indonesian? I am also an Indonesian translator. If allowed I will be happy to start translating this project. :)

Thank you.

**Comment by anaufalm** [comment]
I've create on my repo here: https://github.com/anaufalm/mostly-adequate-guide-id

I'll update translation, and pull request every 1000 word, and can you merge to master? (after your review of course) :)

**Comment by KtorZ** [comment]
Hey! Good to know that the book is spreading :) 
For new translations, please follow the [guidelines about translations](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/CONTRIBUTING.md#Translations) . I'll create an Indonesian team and add you as the owner of the team. The way you manage your repository (PR, branches etc.) is then up-to-you. If you need to add new member to the team, please let me know.

In the meantime, I invite you to transfer your current repo to the MostlyAdequate organization :+1:

**Comment by anaufalm** [comment]
Im glad to hear that, thank you. :)

Can Indonesia repo kept in my repo? (https://github.com/anaufalm/mostly-adequate-guide-id) If translate I've reviewed, I will branch, and start a PR to master repo.

**Comment by anaufalm** [comment]
Okey, I got it :)

**Comment by gomenasai-io** [comment]
Can I join this project? @anaufalm @KtorZ

**Comment by KtorZ** [comment]
Hi, @gomenasai-io, @anaufalm should be able to invite you to the team :+1:
If not, please let me know.

**Comment by gomenasai-io** [comment]
Can you invite me to the team, @KtorZ? I think @anaufalm will be glad if I help this project quickly.

**Comment by mirzazulfan** [comment]
Hi @anaufalm and @KtorZ.
Can i join the team? very interesting to join this project. I do my best. 
Thanks.
Best regard my bro.

**Comment by anaufalm** [comment]
Hi, @gomenasai-io, @mirzazulfan good to know you wanna help this book. You can be part of team.
But before you work, please read discussion team first

**Comment by anaufalm** [comment]
Hi, @KtorZ, can you set my Temporary interaction limits become more? because I will make a commit file per 1000+ words or fewer in each commit.

**Comment by KtorZ** [comment]
Hi @anaufalm, you don't have any limits so I am no sure to understand what your issue is and where it comes from ?

**Comment by anaufalm** [comment]
I get notice like this @KtorZ 
![screenshot_48](https://user-images.githubusercontent.com/35919168/36934574-68f67a40-1f1e-11e8-9f1f-5bebaf7383f5.png)

**Comment by KtorZ** [comment]
Weird. Your permissions were back to "read-only" on the repo. 
Please try again,

**Comment by anaufalm** [comment]
This is I am confused, even though a few hours ago I still can commit. 
Thanks for fixing,
