### ISSUE TITLE
How can I run my code in the terminal?

### ISSUE THREAD

**Issue by peterstorm** [MostlyAdequate/mostly-adequate-guide#384]
I usually use node to run my simple javascript, but how can I use it with libraries too? I'm quite new to all this.

**Comment by KtorZ** [comment]
Hey @peterstorm! 
Welcome!
You might want to have a look at [npm](https://docs.npmjs.com/), the de facto Node.js package manager as well as the [module API](https://nodejs.org/api/modules.html#modules_modules). The documentations are quite extensive on the topic and really good to get started with!

**Comment by peterstorm** [comment]
Hi @KtorZ ! :)

I figured it out. I just of course had to declare the helper functions in my js file as well, so I could play with the code.
