### ISSUE TITLE
flickr example without jquery?

### ISSUE THREAD

**Issue by peterstorm** [MostlyAdequate/mostly-adequate-guide#388]
Hello!

I'm trying to rewrite the flickr example from the book, without using jQuery, and I've gotten the API call to work with a fetch request again, and I think in a pretty 'functional' way.
But I can't for the life of me rewrite this line:
`const img = src => $('<img />', { src });`
How would I do that with vanilla JS, and still keep in the FP spirit?
I've tried to do:
`const img = src => document.createElement('img').setAttribute('src', src)`
But it doesn't work :(

**Comment by KtorZ** [comment]
Hey! You're almost there. 
Should you look at the [signature of the `setAttribute` method](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute), you'll see it actually returns nothing (a.k.a `undefined`). On the other hand, fat-arrows, when used in a single-expression way (like you did) return this single expression as a result. So, basically, your function has the following type signature:

```hs
img :: String -> ()
```

By looking at the signature, you can pretty much see that there's something nasty going on ^.^
You may want to try this instead:

```js
const img = (src) => {
  let el = document.createElement('img');
  el.setAttribubte('src', src);
  return el;
}
```

:+1:
