### ISSUE TITLE
Chapter 11 Exercise 2 getUserName is undefined in Exercise

### ISSUE THREAD

**Issue by RinatRezyapov** [MostlyAdequate/mostly-adequate-guide#418]
Using `eitherToTask`, simplify `getUserName` to remove the nested `Either`.

// findNameById :: Number -> Task Error (Either Error User)
const findNameById = compose(map(map(prop('name'))), findUserById);

getUserName is undefined in Exercise

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/exercises/ch11/exercise_b.js

**Comment by KtorZ** [comment]
Indeed. This issue is currently addressed by #415, haven't got time to fully review and merge it.
Thanks for reporting :)

**Comment by KtorZ** [comment]
Close with #415
