### ISSUE TITLE
Ch3 typo: "ringer" should be "wringer"

### ISSUE THREAD

**Issue by bschuth-alphce** [MostlyAdequate/mostly-adequate-guide#444]
Minor typo; I have made the change and can generate a PR for this now if you'd like. I'm not sure how you like to handle these little changes, and I'm brand new here, so I don't want to start making PRs without asking.

**Comment by KtorZ** [comment]
Best place to look at (and that's true for most OSS repository) is here: [CONTRIBUTING.md](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/CONTRIBUTING.md)

Hence, feel free to open a PR if you have small correction to do, they're very welcome!
