### ISSUE TITLE
Chapter 5's example fails

### ISSUE THREAD

**Issue by 4096void** [MostlyAdequate/mostly-adequate-guide#447]
Line below cannot generate the result on the right.
I guess the code above is insufficient to this result.
https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch05.html#functional-husbandry
`const lastUpper = compose(toUpperCase, head, reverse); // 'UPPERCUT'`

**Comment by KtorZ** [comment]
May you please elaborate a bit more ^.^ ?
What is "the code above" and in what context ?

**Comment by 4096void** [comment]
```javascript
// compose just take 2 functions than return a new one
const compose = (f, g) => x => f(g(x)); 


// but following cases here take 3 even 4 functions to generate a new function.
// I want to know how to do that.
const lastUpper = compose(toUpperCase, head, reverse);
const loudLastUpper = compose(exclaim, toUpperCase, head, reverse);
````

**Comment by KtorZ** [comment]
Hmmm. Fair point. 
It would be nicer to introduce the variadic compose and it's simplified version 'compose2` as above. 

Relates to #443 .

**Comment by 4096void** [comment]
I find compose in Appendix A is what I need https://mostly-adequate.gitbooks.io/mostly-adequate-guide/appendix_a.html#compose

**Comment by KtorZ** [comment]
It is indeed, and should be mentioned early in the chapter 5 to avoid confusion.
