### ISSUE TITLE
Sequence implementation for Left

### ISSUE THREAD

**Issue by ivan-kleshnin** [MostlyAdequate/mostly-adequate-guide#450]
[Chapter 12](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch12.html#type-feng-shui) proposes the following implementations of `Right#sequence` and `Left#sequence`:

```js
class Right extends Either {
  sequence(of) {
    return this.$value.map(Either.of);
  }
}

class Left extends Either {
  sequence(of) {
    return of(this);
  }
}
```

Which leads to an invalid type signature in the `Left` case:

```js
// Either a (Maybe String) -> Maybe (Either a String)
new Right(new Just("x")).sequence(Maybe.of)
// => Just(Right('x')) // Maybe (Either a String) -- fine !!!

new Left(new Just("x")).sequence(Maybe.of)
// => Just(Left(Just('x'))) // -- wrong !!! @_@
```

In Haskell, `sequence` does not affect `Left` outer wrapper at all:

```
λ> sequence (Right (Just ()))
Just (Right ()) -- swapped containers
λ> sequence (Left (Just ()))
Left (Just ()) -- did nothing !!!
```

**Comment by KtorZ** [comment]
Hmmm... Your code excerpt doesn't compile in my head ^^" ... Or we aren't talking about pure functions anymore :p ... There's some implicit type inference going on here that makes you think there's an issue. 
Giving _GHC_ a bit of help we can sort it out:

```hs
λ> let sequenceSpecialized = sequence :: Either (Maybe ()) (Maybe ()) -> Maybe (Either (Maybe ()) ()) 
λ> sequenceSpecialized (Right (Just ()))
-- Just (Right ())
λ> sequenceSpecialized (Left (Just ()))
-- Just (Left (Just ()))
```

The implementation is actually fine :) Make sure to do a type-analysis to convince yourself (or me :p).

**Comment by ivan-kleshnin** [comment]
I have no intuitive idea how bifunctors are supposed to be rewrapped inside-out and the book does not cover it either. It talks about `t (f a) -> f (t a)` but Either is `t (f1 a) (f2 a)` so... Maybe you know a good resource on the topic?

**Comment by KtorZ** [comment]
Note that in this case, Bifunctors aren't involved and we treat `Either a` as a Functor (an Applicative exactly), and that's why we talk about `Either a` and not `Either`. 

I recommend you this reading (and all the other chapters of the same serie) by Tom Harding:

http://www.tomharding.me/2017/06/26/fantas-eel-and-specification-18/

Great stuff :)

**Comment by ivan-kleshnin** [comment]
Thank you! I even feel I kinda got it 😄 

```
Either _ (Maybe ()) -> Maybe (Either _ ()) 
```
