### ISSUE TITLE
Translation to Thai language

### ISSUE THREAD

**Issue by mahasak** [MostlyAdequate/mostly-adequate-guide#455]
Hi,

My name is Max, I'd like to start a translation "Mostly Adequate" to Thai language.
I've 6-8 hours per weeks to do translation this book into Thai language. 

Please add me to organization.

Cheers,
Max

**Comment by mahasak** [comment]
I will update translation progress in this issue until point that we can hand over this fork to organization !!

**Comment by KtorZ** [comment]
Hi @mahasak !
Translations are really welcome. Make sure to keep track of which revision you're translating from as the book gets updated rather often. 

Make sure to read the contribution guidelines:

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/CONTRIBUTING.md#Translations

I'll create a proper team and invite you there :)
