### ISSUE TITLE
compose method's type signature 

### ISSUE THREAD

**Issue by lin1987www** [MostlyAdequate/mostly-adequate-guide#468]
// compose :: ((a -> b), (b -> c),  ..., (y -> z)) -> a -> z
const compose = (...fns) => (...args) => fns.reduceRight((res, fn) => [fn.call(null, ...res)], args)[0];

I think it should be
// compose :: ( (y -> z), ..., (b -> c), (a -> b)) -> a -> z

**Comment by Mattsi-Jansky** [comment]
My study group noticed this too, but rather than flip the first part I think it should be: 

// compose :: ((a -> b), (b -> c), ..., (y -> z)) -> z -> a

i.e., functions are still listed a-z but because the last function evaluated first, it returns a function that takes z and returns a.

**Comment by lin1987www** [comment]
If it returns a function that takes z and returns a, it should be:

// compose :: ((b -> a), (c -> b), ..., ( z -> y)) -> z -> a

It should flip these functions in first part.

**Comment by Mattsi-Jansky** [comment]
Ah, good point. Perhaps your first version was more readable. It's an awkward one to parse either way.

**Comment by KtorZ** [comment]
Fixed with #549 :tada:
