### ISSUE TITLE
HTML version pointing to non existing markdown page.

### ISSUE THREAD

**Issue by vicneanschi** [MostlyAdequate/mostly-adequate-guide#469]
Here https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch11.html#all-natural
link to `free theorem` https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch7.md#free-as-in-theorem

**Comment by KtorZ** [comment]
Thanks for reporting! This was fixed by d33c6aa!
