### ISSUE TITLE
Nitpicking on example in chapter 8

### ISSUE THREAD

**Issue by eevman** [MostlyAdequate/mostly-adequate-guide#479]
In "My First Functor", there is this example:
``` javascript
Container.of('bombs').map(concat(' away')).map(prop('length')); 
// Container(10)
```
Assuming that `concat` is defined as in appendix C:
``` javascript
const concat = curry((a, b) => a.concat(b));
```
`Container.of('bombs').map(concat(' away'))`
gives the result 
```
Container(' awaybombs')
```
and not
```
Container('bombs away')
```
which I suppose was the intended meaning...
Of course both give the final answer 10 :-)
Shouldn't the example be:
``` javascript
Container.of('bombs').map(append(' away')).map(prop('length')); 
// Container(10)
```
where `append` is:
``` javascript
const append = flip(concat);
```
or something similar?
Or is maybe `concat` defined as
``` javascript
const concat = curry((a, b) => b.concat(a));
```
but then it would be difficult to know what function `concat` does without looking at the implementation...
Any thoughts on this?

**Comment by KtorZ** [comment]
Indeed, this was already reported by someone not so long ago. We should definitely have an `append` function here :)

**Comment by eevman** [comment]
A followup question: shouldn't we add `append` to Appendix C? It is only mentioned in [example in Chapter 5](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/f4a1c4bbcb2187047025af4665f3f5a3d8408d58/exercises/ch05/solution_c.js#L1)

I have found the [report](https://github.com/MostlyAdequate/mostly-adequate-guide/pull/404#issuecomment-369045206).

**Comment by eevman** [comment]
Further on in chapter 8, there's this strange example:
``` javascript
const compLaw1 = compose(map(concat(' world')), map(concat(' cruel')));
const compLaw2 = map(compose(concat(' world'), concat(' cruel')));

compLaw1(Container.of('Goodbye')); // Container(' world cruelGoodbye')
compLaw2(Container.of('Goodbye')); // Container(' world cruelGoodbye')
```
This was changed in #191. I wonder why didn't they use `append` instead of changing the output to be correct in a strange way? :-)
