### ISSUE TITLE
Chapter 1: How is the `identity` property simplifying code when we don't know flockC's value?

### ISSUE THREAD

**Issue by jLouzado** [MostlyAdequate/mostly-adequate-guide#490]
The code sample is as shown below

```js
// Original line
add(multiply(flockB, add(flockA, flockC)), multiply(flockA, flockB));

// Apply the identity property to remove the extra add
// (add(flockA, flockC) == flockA)
add(multiply(flockB, flockA), multiply(flockA, flockB));

// Apply distributive property to achieve our result
multiply(flockB, add(flockA, flockA));
```

Once we know that `FlockC` is zero then yes, we can replace `add(flockA, flockC)` with just `flockA` but if this were an algorithm we were writing there would be no way to know that flockC is `0` at that point right?

**Comment by DrBoolean** [comment]
You are right. The example has hardcoded values for the flocks so it is assumed to be 0, but if it was dynamic, that wouldn't be the case

**Comment by iheshime** [comment]
@jLouzado It made me confused too. But at the end, I find:
```javascript
var flock_a = 4;
var flock_b = 2;
var flock_c = 0;
```
and problem solved.
