### ISSUE TITLE
Ch 13: (Maybe) the First Monoid can implement empty()

### ISSUE THREAD

**Issue by mateusmlo** [MostlyAdequate/mostly-adequate-guide#516]
So I was looking at how the Chapter 13 is going and at the section [Not quite a monoid](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/ch13.md/ch13.md#not-quite-a-monoid) is said that the First monoid can't really be one since it doesn't implement an Identity, but it just so happens that it can implement a Nothing() from Maybe as an empty for itself and be 'concat'ed around. 
This is kind of a workaround for the laws of Monoids if I understood it correctly, so it might be the reason you authors decided to leave First itself as "not quite a monoid" since it needs a little help to be "lifted" from Semigroup into this category.
Sorry if this issue is wrong, I'm doing my best to understand the concepts and laws, had to overclock my brain to understand a few :crying_cat_face: 

Inspired from the [Crocks' docs](https://evilsoft.github.io/crocks/docs/monoids/First.html)

**Comment by DrBoolean** [comment]
Thanks for saying something! I'm aware of the work around and it's definitely useful despite not being excepted throughout the "purest" community. I want to leave it as is, but add a comment about the Maybe workaround it since you are the second person to bring it up.

**Comment by kapooostin** [comment]
There are interesting thoughts on the topic https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/
