### ISSUE TITLE
[Chapter 12] sequence got  undefined

### ISSUE THREAD

**Issue by xielehe** [MostlyAdequate/mostly-adequate-guide#525]
I'm very thankful for this resource.I run following codes in the terminal, got undefined.
`const { Maybe, sequence, List } =  require('@mostly-adequate/support');
console.log(sequence(List.of, Maybe.of(['the facts'])))
`
Am I wrong?

**Comment by KtorZ** [comment]
Hey! It appear that a `return` statement was missing for the `sequence` function on `Maybe`. This was recently fixed. May you try with `@mostly-adequate/support@2.0.1` ?

**Comment by xielehe** [comment]
@KtorZ Thank you very much, I learn a lot from your book.

**Comment by KtorZ** [comment]
Appreciated!
I am forwarding your thank you to @DrBoolean, the original author of the book :smile:
