### ISSUE TITLE
Is this an old book?

### ISSUE THREAD

**Issue by Brennvo** [MostlyAdequate/mostly-adequate-guide#539]
https://drboolean.gitbooks.io/mostly-adequate-guide-old/content/

How come the URL says this is old?

**Comment by KtorZ** [comment]
Hey :)
You've found an old link indeed. The repository used to be hosted there before and later moved to:

https://mostly-adequate.gitbooks.io/mostly-adequate-guide/

The one from your link is several years old and lacks of many updates that have been added between then and now.
