### ISSUE TITLE
Gitbooks url offline

### ISSUE THREAD

**Issue by nicobrinkkemper** [MostlyAdequate/mostly-adequate-guide#543]
The readme refers to [https://mostly-adequate.gitbooks.io/mostly-adequate-guide/](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/), but this link is offline. (ipadress not found)

**Comment by kosich** [comment]
It is working for me now.  
Can you still reproduce it?

_Sorry to mention, but also check you're not using any VPN, just in case. If it's reproducible, we'll dig further._

**Comment by flauwekeul** [comment]
From my location (The Netherlands) I can't visit gitbooks.io at all (not just mostly-adequate.gitbooks.io). However, when I connect to a VPN from the US, gitbooks.io works fine.

It seems to be a problem of gitbooks.io.

**Comment by sugoidesune** [comment]
I am having this problem aswell, but only with a particular modem/internet provider.
Doesn't work at home and at friends. Works via mobile and at work.
I have yet to understand the explanation of the the internet provider.

**Comment by KtorZ** [comment]
I am afraid this isn't a problem we can really deal with. We are not in charge of maintaining Gitbook's server and so far, they seem to work fine for most people. 
They recently had an issue with their SSL certificates being expired which may be caused issues to some of you accessing the domain during that period. This seems however now resolved. 

If the problem persists or, start affecting too many users, I may setup `gh-pages` and host the book directly on Github.
