### ISSUE TITLE
Typo in definition of pureHttpCall?

### ISSUE THREAD

**Issue by kretep** [MostlyAdequate/mostly-adequate-guide#544]
In chapter 3, section 'The case for purity', shouldn't this:

`const pureHttpCall = memoize((url, params) => () => $.getJSON(url, params));`

be

`const pureHttpCall = memoize((url, params) => $.getJSON(url, params));`

**Comment by KtorZ** [comment]
I suggest you read again this very paragraph and give a special attention to the section following the definition of this function :) 

The definition is correct. Happy to answer any question you may have after this.
