### ISSUE TITLE
Ch.8 exercises -> showWelcome 'append' => 'concat' 

### ISSUE THREAD

**Issue by dupdup** [MostlyAdequate/mostly-adequate-guide#545]
Can you please update the `showWelcome` function in exercises section

const showWelcome = compose(append('Welcome '), prop('name'));
//"AliWelcome "
const showWelcome = compose(**concat**('Welcome '), prop('name'));
//"Welcome Ali"

**Comment by chuckwondo** [comment]
I just came across this as well. Why did you close this?

**Comment by dupdup** [comment]
it is right on the inner text exercises/ch08/exercise_c.js and also right on npm
