### ISSUE TITLE
Chapter 4, pure functions

### ISSUE THREAD

**Issue by mohaalak** [MostlyAdequate/mostly-adequate-guide#563]
in chapter 4 in section **More Than a Pun / Special Sauce** it says

> When we spoke about pure functions, we said they take 1 input to 1 output. 

I don't remember anywhere in the book prior to this sentence we established that pure functions should accept only 1 input or argument and even after searching in other resources I can't find anywhere that is the case for pure functions.

**Comment by KtorZ** [comment]
There's a whole section about this in Chapter 3, maybe you missed it :sweat_smile:  

--> https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch03.md#8th-grade-math

Although, I think your confusion comes from the term "input" and the meaning it's given in this sentence. "take 1 input to 1 output" doesn't mean that the function must have one single argument and return one single result, but that for a given distribution of argument (a.k.a the input of the function), it must necessarily return the same result (a.k.a the output). 

If you step back a bit, any function with several argument can actually be considered as a function with a single argument by using an encapsulating data structure. For instance in JavaScript, consider the following:

```js
function add(a, b) { return a + b }
```

A function of arity 2 that could as well be written: 

```js
function add([a, b]) { return a + b }
```

which suddenly becomes a function of arity 1. This is a bit artificial in JavaScript or languages which don't have proper support for Tuples, but take Elm, Rust or Haskell this can be made even more obvious. Similarly, most languages only allow one output result, but some like Go gives you the ability to return several. That is however equivalent to returning a tuple of results. 

Therefore, the term input here really refers to "whatever arguments are passed to the function".

**Comment by SeyyedKhandon** [comment]
I had been confused at that point too. now thanks to @KtorZ  which explained the meaning of the mentioned line in the chapter of the book, i have more clear of the pureFP.

SO, wouldn't it be a good one to considering the change of the line  to more proper one? like :
based on wikipedia:
" When we spoke about pure functions, Its return value is the same for the same arguments. "
or  add a conclusion to the chapter 4 like wiki did:

In computer programming, a pure function is a function that has the following properties:[1][2]

1. Its return value is the same for the same arguments (no variation with local static variables, non-local variables, mutable reference arguments or input streams from I/O devices).

2. Its evaluation has no side effects (no mutation of local static variables, non-local variables, mutable reference arguments or I/O streams).

Thus a pure function is a computational analogue of a mathematical function. Some authors, particularly from the imperative language community, use the term "pure" for all functions that just have the above property 2[3][4] (discussed below).
