### ISSUE TITLE
Link to gitbooks not working

### ISSUE THREAD

**Issue by arafat36** [MostlyAdequate/mostly-adequate-guide#567]
![image](https://user-images.githubusercontent.com/43789843/80291757-c0342e00-8750-11ea-9cf7-f0c1b443f6da.png)
![image](https://user-images.githubusercontent.com/43789843/80291779-f70a4400-8750-11ea-9eb2-afed6b93d1b5.png)

...or is it just me :)

**Comment by s0kil** [comment]
It looks like a problem on your side, maybe DNS server.

**Comment by arafat36** [comment]
I was able to access the website last week, but then it just stopped working from then. I thought it's something temporary, but still not working. I don't know how to fix this, and I'd appreciate any help

**Comment by s0kil** [comment]
What if you try outside of browser?
```bash
curl -LI https://mostly-adequate.gitbooks.io/mostly-adequate-guide/
```

**Comment by arafat36** [comment]
I got the following:
![image](https://user-images.githubusercontent.com/43789843/80292482-4e131780-8757-11ea-9f69-583eafe96460.png)

**Comment by s0kil** [comment]
It's looking like a DNS error.
Have you switched DNS servers recently?

**Comment by arafat36** [comment]
No, I don't know how to do that

**Comment by s0kil** [comment]
https://support.apple.com/guide/mac-help/test-dns-server-network-utility-mac-mchlp1698/10.15/mac/10.15

**Comment by arafat36** [comment]
My dns server is 
```DNS Servers . . . . . . . . . . . : 192.168.1.1```

**Comment by s0kil** [comment]
You could try use the Cloudflare DNS, if you scroll down they have instructions for macOS
https://1.1.1.1/dns/

**Comment by arafat36** [comment]
Okay, now it's working! 👍 
I changed the DNS servers to Cloudflare's.
```DNS Servers . . . . . . . . . . . : 1.1.1.1 1.0.0.1```
Thanks for taking the time! Appreciate it!

**Comment by s0kil** [comment]
I'm glad to help!
