### ISSUE TITLE
Reconciling Testability of pointfree-code

### ISSUE THREAD

**Issue by jLouzado** [MostlyAdequate/mostly-adequate-guide#568]
RE: https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch03.html#testable

> It's beyond the scope of this book, but [...] try Quickcheck

_Note: Asking here because not sure where else to direct this question._

So if a function has types it's fine, but when a function is pointfree how would a tool like Quickchek even know what input types to test against?

**Comment by KtorZ** [comment]
Hi, I am not sure to understand your question and why you seem to oppose "a function with types" and "a pointfree function"? 

Pointfree is just a writing style for the function body. Any pointfree function can be written with explicit argument passing. Being pointfree doesn't prevent the function from having typed inputs and typed outputs :thinking: 

Perhaps I am missing the point of your question? (no pun intended).

**Comment by jLouzado** [comment]
> Hi, I am not sure to understand your question and why you seem to oppose "a function with types" and "a pointfree function"?

Sorry @KtorZ, I think I should've been clearer. Yes, point-free functions can have types but my primary experience of writing point-free functions is with ramda and we've found it very difficult to integrate ramda & types

> Pointfree is just a writing style for the function body. Any pointfree function can be written with explicit argument passing. Being pointfree doesn't prevent the function from having typed inputs and typed outputs 🤔
> 

Closing this question for now, maybe I'll go read up some more on this.

> Perhaps I am missing the point of your question? (no pun intended).

Nice 😏

**Comment by KtorZ** [comment]
By the way: point-free is definitely not a style I'd recommend for anything beyond abstract libraries / code working with high-level abstraction. 
When working with things like Functor or Applicative, small and abstract identifiers (`a`, `f a` etc..) are somewhat more readable, and composition usually works well. This is why languages like Haskell also have so many operators around these abstractions `.`, `<$>`, `<$`, `$>`, `<*>`, `*>`, `<*`, `&`, `<&>` ... they play nicely together and can be very expressive. 

Yet, as soon as we reach code that is touching business logic and is more "application-level", point-free can just be cryptic and makes it hard to decipher code. So, to be use with care.
