### ISSUE TITLE
CH9: mcompose is not explained

### ISSUE THREAD

**Issue by admhemed** [MostlyAdequate/mostly-adequate-guide#570]
> const mcompose = (f, g) => compose(chain(f), g);
> 
> // left identity
> mcompose(M, f) === f;
> 
> // right identity
> mcompose(f, M) === f;
> 
> // associativity
> mcompose(mcompose(f, g), h) === mcompose(f, mcompose(g, h));
> 

How can we conclude `mcompose(M, f) === f` ?

**Comment by KtorZ** [comment]
Hey :) 
These are _laws_, and in this regard, they are not something we "conclude", but rather, something we ought to satisfy. Said differently, these are _requirements_ any implementation of a Monad should satisfy in order for it to be called a Monad.

**Comment by admhemed** [comment]
> Hey :)
> These are _laws_, and in this regard, they are not something we "conclude", but rather, something we ought to satisfy. Said differently, these are _requirements_ any implementation of a Monad should satisfy in order for it to be called a Monad.

Thanks for your answer. I just wish the book states that explicitly. I think it is big assumption to think this is a common knowledge.

**Comment by sevillaarvin** [comment]
Is it correct to assume that `M` here stands for the `.of` function aka identity? I tried it (below) and it seems to work.

```js
#+begin_src js :noweb no-export :results code
  <<js compose>>
  <<js chain>>
  <<js maybe monad>>

  const mcompose = (f, g) => compose(chain(f), g)

  // left identity
  // mcompose(M, f) === f

  // right identity
  // mcompose(f, M) === f

  // associativity
  // mcompose(mcompose(f, g), h) === mcompose(f, mcompose(g, h))

  const maybeAddOne = (x) => Maybe.of(x + 1)

  const leftIdentity = mcompose(Maybe.of, maybeAddOne)(123)
  const rightIdentity = mcompose(maybeAddOne, Maybe.of)(123)

  return {
    leftIdentity,
    rightIdentity
  }
#+end_src

#+RESULTS:
#+begin_src js
{ leftIdentity: Maybe { val: 124 }, rightIdentity: Maybe { val: 124 } }
#+end_src
```
