### ISSUE TITLE
Apply.ap() looks incorrect (?)

### ISSUE THREAD

**Issue by manuscriptmastr** [MostlyAdequate/mostly-adequate-guide#579]
Hello FP friends! I am using this book as a "sanity check" for an FP workshop at my company.

I noticed that in the Appendix and any examples with `.ap()`, the first container holds a function while `.ap()` passes it a container with any value. This appears to be opposite of the [Fantasy-land specification](https://github.com/fantasyland/fantasy-land#fantasy-landap-method), where the content of `.ap()` must be a container _with a function_. Otherwise the law of composition fails.

```js
import R from 'ramda';

// Mostly Adequate Guide, Appendix B:
class Identity {
...
ap: other => other.map(this.value)
...
}
Identity(R.add).ap(Identity(1)).ap(Identity(2)) // Identity(3)

// Fantasy-Land/Sanctuary-Identity:
class Identity {
...
ap: other => other.value(this.value)
...
}
Identity(1).ap(Identity(R.add(2))).ap(Identity(R.add(3)) // Identity(6)

// Law of composition:
Identity(1).ap(Identity(R.add(2)).ap(Identity(R.add(3)).map(f => g => x => f(g(x))))) // Identity(6)
// Is equivalent to
Identity(1).ap(Identity(R.add(2))).ap(Identity(R.add(3))) // Identity(6)
```

I am fairly new to containers — am I lying here 😄? (This difference is also the case with `Task` and possibly other containers in the Appendix)

See:
- [`fantasy-land/apply`](https://github.com/fantasyland/fantasy-land#apply)
- [`sanctuary-identity/ap`](https://github.com/sanctuary-js/sanctuary-identity/blob/d25f7c26e041a71542e60b7581e235212da9177b/index.js#L256)

**Comment by KtorZ** [comment]
Indeed, the arguments are swapped compared to fantasy-land. Mostly adequate `ap` follows the following signature:

```
ap :: f (a -> b) -> f a -> f b
```

where the first argument is implicitly `this`. 

There's nothing _incorrect_ per se about it, it is just different from what fantasy-land specifies, like several other thing in the book currently. We discussed in the past about whether or not the book should follow the specs from fantasy-land; yet the book isn't about fantasy-land, it's about FP in general, and some concepts are better taught in a way that sometimes differ from fantasy-land (this one is an example, I do _prefer_ the way `ap` is defined in the mostly-adequate guide for it is easier to reason about it). 

I hope this answers your concerns :blush:

**Comment by manuscriptmastr** [comment]
@KtorZ Thanks for the clarification! I didn't realize there was more than one way to define these behaviors 🤷‍♂️.
