### ISSUE TITLE
Gitbook appears to be stale/behind master

### ISSUE THREAD

**Issue by etmoore** [MostlyAdequate/mostly-adequate-guide#597]
It appears the [Gitbook version](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/content/) is out of date (ie behind master).
 
evidence noticed so far:
* Under ch8 [A Spot of Theory](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/content/ch08.html#a-spot-of-theory), I see `Container(' world cruelGoodbye')` in gitbook, but master correctly shows "Goodbye cruel world". 
    * gitbook: ![image](https://user-images.githubusercontent.com/3310531/107128015-5cff2c80-6888-11eb-9b37-42e5a1b44044.png)
    * master: 
![image](https://user-images.githubusercontent.com/3310531/107128058-bc5d3c80-6888-11eb-8e74-2f2bb9d8f416.png)
* Gitbook does not have an `append` function in Appendix c, but master [does](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/appendix_c.md#append).

Any chance the Gitbook version can be updated? 🙏

**Comment by etmoore** [comment]
🤔  Looks like something was changed/updated, as I now see "Goodbye cruel world" in the gitbook  ([here](https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch08#a-spot-of-theory))
![image](https://user-images.githubusercontent.com/3310531/107630699-ebc9cb80-6c31-11eb-9dfa-58fbe0d65e64.png) … and I see `append` in appendix C now ([here](https://mostly-adequate.gitbook.io/mostly-adequate-guide/appendix_c#append)). 
![image](https://user-images.githubusercontent.com/3310531/107630924-4105dd00-6c32-11eb-9f16-93af001ca004.png)


Cool 👍  Thanks!  Closing.

**Comment by KtorZ** [comment]
Yes, sorry for not notifying. I attempted a migration on gitbook but was dragged into something else and didn't have time to check if it did work or not. Sounds like it did :)

**Comment by etmoore** [comment]
@KtorZ The text is updated (❤️), but the migration appears to have resulted in a few other issues 😬 
1. Exercises no longer work… they're just static text  (see https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch04#lets-practice)  
<img width="704" alt="image" src="https://user-images.githubusercontent.com/3310531/109298586-d8a62680-7801-11eb-8014-732e0c215fa2.png">

2. The book logo is broken  
<img width="283" alt="image" src="https://user-images.githubusercontent.com/3310531/109298577-d2b04580-7801-11eb-9782-48b1a70bc399.png">

3. The sub-chapter navigation on the left side of the page doesn't work. Rather than linking to the appropriate header, it links to a subpath that doesn't exist.  eg `ch03/oh-to-be-pure-again`  instead of `ch03#oh-to-be-pure-again`
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/3310531/109298753-13a85a00-7802-11eb-8825-c5788c192dac.png">
The good news is that the "Contents" navigation in the top right corner does work.

Happy to create separate issues for these if you'd like! Appreciate your help 😄

**Comment by etmoore** [comment]
Ah, I see another issue has already been created for the broken in-browser exercises: https://github.com/MostlyAdequate/mostly-adequate-guide/issues/608
