### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by mdavidgreen** [MostlyAdequate/mostly-adequate-guide#6]
Would you like some help adding semicolons to your code examples, or do you feel strongly about not using them? I notice you tend to leave them out in a lot of cases, but it's done inconsistently, so I wasn't sure what your intention was.

**Comment by syzer** [comment]
return statement do not need a semicolon?

**Comment by DrBoolean** [comment]
I was thinking semicolons might just be a hassle while learning. Like putting make-up on a frog before dissecting it. That said, I have work to do to remove ones I subconsciously included...

**Comment by mdavidgreen** [comment]
Students may be distracted when their linting tools with default settings tell them the code samples are full of errors due to missing semicolons. I'd be glad to help touch up your frog's lipstick and eyeliner, but I didn't want to presume, so let me know.

**Comment by DrBoolean** [comment]
Ahh, good thinking. I suppose they are necessary after all. I'm grateful for any help. Thanks a lot!

**Comment by shama** [comment]
My 2 bits. I have found semicolons to be confusing to people new to JavaScript as they are not obvious where they should and should not go. It is also perfectly valid to omit them and configure tooling to not warn when you prefer semicolons unwelcome.

Here are some additional opinions:
* http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding
* http://inimino.org/~inimino/blog/javascript_semicolons
* https://gist.github.com/ryanflorence/61935031ff729f072d9b

Also a shamelessly made video on the subject:
* https://www.youtube.com/watch?v=gsfbh17Ax9I 

Although a good reason, IMO, to use semicolons is people will not get unreasonably angry at you if you *do* use semicolons but they oft do when you don't. In light, I'm not here to argue about semicolons but just inject my opinion on this open issue.

Thanks for this fantastic project!
