### ISSUE TITLE
Link to installing ebook-convert is broken

### ISSUE THREAD

**Issue by jacobpmeyer** [MostlyAdequate/mostly-adequate-guide#609]
The link on line 66 of the README is broken and needs to be updated to a working link.

**Comment by codingedgar** [comment]
the movi links just gets me to gitbook landing page

**Comment by jacobpmeyer** [comment]
https://github.com/MostlyAdequate/mostly-adequate-guide/pull/611

**Comment by KtorZ** [comment]
Fixed in #611
