### ISSUE TITLE
Can't push local branch to origin

### ISSUE THREAD

**Issue by jacobpmeyer** [MostlyAdequate/mostly-adequate-guide#610]
Tried to push a local branch that addresses [Issue #609](https://github.com/MostlyAdequate/mostly-adequate-guide/issues/609) so that I could open a pull request, but was met with a permission error/denial.

**Comment by KtorZ** [comment]
That is normal. The standard way of doing this is by:

a) Forking the repository on your own account
b) Push the branch on your forked repository
c) Make a pull request to the upstream repository

**Comment by jacobpmeyer** [comment]
Thank you!
