### ISSUE TITLE
Download files not accessible

### ISSUE THREAD

**Issue by wes-novack** [MostlyAdequate/mostly-adequate-guide#626]
The [README now links](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/README.md#download-it) to GitHub Workflows (Actions) to download book artifacts, but the [latest one](https://github.com/MostlyAdequate/mostly-adequate-guide/actions/runs/802457659) from 3 months ago has "expired" artifacts that cannot be downloaded.

**Comment by suside** [comment]
I've created PR #627 with fix, for now you can download files from [my fork](https://github.com/suside/mostly-adequate-guide/releases/latest)

**Comment by wes-novack** [comment]
Curious, why is there no longer a .mobi file format to download?

**Comment by KtorZ** [comment]
Gitbook has dropped support for .mobi format in their new implementation. And, while there _probably_ exists some converters from epub to mobi or whatnot, I didn't really took any time to investigate it :blush:
