### ISSUE TITLE
Instructions for running Exercises are incorrect

### ISSUE THREAD

**Issue by AndreyNikiforov** [MostlyAdequate/mostly-adequate-guide#640]
I am following [instructions for running exercises locally](https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch04#running-exercises-on-your-machine-optional) and `npm install` fails with the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @mostly-adequate/exercises@1.0.0
npm ERR! Found: eslint@5.16.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^5.9.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.9.0" from eslint-config-airbnb@16.1.0
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^16.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/node/.npm/_logs/2023-02-18T19_36_11_612Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-02-18T19_36_11_612Z-debug-0.log
```

Steps to repro:
- clone repo
- open vscode with that folder
- use "Reopen in Container" and choose "Node.js & Typescipt" with v18 from the list
- follow [instructions from the book](https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch04#running-exercises-on-your-machine-optional)

Expected behavior:
- show results of the test run (`npm run ch04`)

Actual behavior:
- fails at `npm install` with error above

**Comment by AndreyNikiforov** [comment]
As a mitigation, upgrade/use `"eslint-config-airbnb": "^17.0.0",` in exercises/package.json/devDependencies

**Comment by aurelienlair** [comment]
Thanks @AndreyNikiforov I faced the same issue but with your suggested it fixed it.
