### ISSUE TITLE
In Chapter 07: Hindley-Milner and Me, why is it said that compose(head, map(f)) is faster than compose(f, head)?

### ISSUE THREAD

**Issue by immadolf** [MostlyAdequate/mostly-adequate-guide#648]
<img width="884" alt="image" src="https://github.com/MostlyAdequate/mostly-adequate-guide/assets/12369197/cdd75230-7daf-457a-8393-ee4a7f1ebe02">

I can't understand this sentence, it seems to me that the time complexity of compose(f, head) is O(1) and the complexity of compose(head, map(f)) is O(n), can anyone help me ?

**Comment by damon314159** [comment]
You've misinterpreted the sentence. It's saying that `compose(f, head)` is faster, which is intuitive as you say

**Comment by immadolf** [comment]
ohh，thks
