### ISSUE TITLE
Seagulls example is confusing to me

### ISSUE THREAD

**Issue by karmatics** [MostlyAdequate/mostly-adequate-guide#67]
It would help if you would explain why the non-functional example got the wrong answer.  I'm not sure what it is trying to do. It would help if you had an English explanation of what conjoin and breed are supposed to do, since they seem (to me) to simply be doing the wrong thing, if you are really treating it as a simplified representation of the real world, rather than purely abstract mathematical operations.

In trying to process it, I started writing out something like this (which might be nice to have in your writeup)....

First, I expanded this:
flock_a.conjoin(flock_c).breed(flock_b).conjoin(flock_a.breed(flock_b))

to this:

flock_a.conjoin(flock_c) 
// flock_a: 4, flock_c: 0  

flock_a.breed(flock_b)
// flock_a: 4, flock_b: 2
 
flock_a.breed(flock_b)
// flock_a: 8, flock_b: 2

flock_a.conjoin(flock_a)
// flock_a: 32

Then, in English:

flock_a.conjoin(flock_c)

flock a, which has 4 seagulls, joins with flock c, which has 0 seagulls, which causes flock a to have its seagulls increased by the number of seagulls in flock b, resulting in flock a still having 4 seagulls and flock c unaffected, still having zero seagulls.

flock_a.breed(flock_b) 

Then flock a (still 4 seagulls) breeds with flock b, which has 2 seagulls.  This results in flock a's number of seagulls being multiplied by the number of seagulls in flock b, leaving b unaffected.  Flock a will now have 8 seagulls, with b still having 2 seagulls.

flock_a.breed(flock_b)

Now flock a (having 8 seagulls) again breeds with flock b (having 2 seagulls).  This results in flock a having 16 seagulls, and flock b remains with 2 seagulls.

flock_a.conjoin(flock_a )

Now flock a conjoins with itself, doubling its numbers to 32. 

I notice that conjoin does not set other.seagulls to zero (you are adding the seagulls to another flock, but still leaving them in their existing flock), and breed does not add the product of breeding to the existing seagulls (i.e. all the parents in "this" are killed by the breeding).  Also it seems wrong to use multiplication at all to represent breeding in this way, it doesn't make sense.  These seem to be logical errors, but are somewhat masked by other things (such as having flock_c having zero members to begin with).

However, it seems the most egregious error is from having a flock conjoin with itself, which doubles its numbers.

Without any sort of English translation or other breakdown of what you are trying to do, it is extremely difficult to tell what it is.

At least with the OO approach, I can figure out what the answer actually represents (the number of seagulls in flock a), and see why it seems to be incorrect.  With the functional approach, "result" may be what you consider correct, but I have no idea what that value actually represents.

**Comment by vjau** [comment]
Take a look at https://github.com/DrBoolean/mostly-adequate-guide/issues/63

**Comment by vjau** [comment]
@DrBoolean : karmatics is not my second account, i swear ! :)

**Comment by karmatics** [comment]
Ha!  yes we seemed have pretty much the same complaints!  (I emailed yesterday and was asked to file an issue today...should have checked the resolved issues first)
