### ISSUE TITLE
Replace is not defined in pointfree example in chapter 5

### ISSUE THREAD

**Issue by bgvianyc** [MostlyAdequate/mostly-adequate-guide#76]
//not pointfree because we mention the data: word
var snakeCase = function (word) {
  return word.toLowerCase().replace(/\s+/ig, '_');
};

//pointfree
var snakeCase = compose(replace(/\s+/ig, '_'), toLowerCase);

**Comment by caasjj** [comment]
How is replace not defined?  String's .toLowerCase returns a String, which has  a .replace method.

**Comment by vjau** [comment]
You have to use the replace function from chapter 4
```js
var replace = curry(function(what, replacement, x) {
  return x.replace(what, replacement);
});
```

**Comment by bgvianyc** [comment]
Perhaps a footnote link or tooltip would make it easier to follow.

**Comment by DrBoolean** [comment]
Yeah, this is definitely an issue... I'm still searching for a good solution for how to reference the support code or prior definitions.
