### ISSUE TITLE
Lack of real world examples

### ISSUE THREAD

**Issue by gyzerok** [MostlyAdequate/mostly-adequate-guide#77]
I've done reading all available chapters in this book and I think that this is the best available guide about FP ever. But the problem is that like others it miss real world examples.
I'm requesting to add chapter with an implementation of some non trivial application, that uses all the staff explained in this books. I suggest to use more complex example than flickr.

**Comment by jirutka** [comment]
+1

**Comment by sdwolf** [comment]
Maybe add this link as a reference? 
http://scott.sauyet.com/Javascript/Talk/2014/01/FuncProgTalk/

**Comment by jirutka** [comment]
@sdwolf Thanks for this link, this is a great presentation!

**Comment by DrBoolean** [comment]
A pure application example is in the works for part2

**Comment by gyzerok** [comment]
@DrBoolean 
Awesome! Is there any way to see drafts for upcoming chapters?

**Comment by AndreasLoukakis** [comment]
Also looking forward for this... great work DrBoolean, much appreciated.

**Comment by AriaMinaei** [comment]
This is hands down the most accessible guide to functional programming. I'm eagerly looking forward to the upcoming chapters. Thanks @DrBoolean :)

**Comment by wpannell** [comment]
:+1: agree wholeheartedly

**Comment by abacaj** [comment]
:+1:

**Comment by emayan** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by gyzerok** [comment]
Any progress on this and on more chapters?

**Comment by DrBoolean** [comment]
Working on it :)  Waiting for more vacation time to really put this over the finish line.

**Comment by dusky3** [comment]
I have to agree with @gyzerok and @AriaMinaei that this is the best guide about FP out there and I'm really looking forward to reading the 2nd part (and the 3rd as well). Thank you @DrBoolean for all your effort, you are a great teacher.

**Comment by jirutka** [comment]
I completely agree too! We are even considering to use this guide as the main guideline in new JavaScript course on our faculty.

**Comment by gyzerok** [comment]
@DrBoolean I'm waiting a real world example to this book more than the Christmas! Is there any progress? :)

**Comment by DrBoolean** [comment]
Hi @gyzerok I'm slowly getting through Traversable/Foldable. I was going to do Monoids after that, but maybe I should do example pt 2 instead.

**Comment by achernyak** [comment]
I would love to see another example. Maybe half way through part 2. This part introduced significantly more information in the first 3 chapters than all of part 1. All of which still seems pretty abstract without a solid real world example.

**Comment by Bondifrench** [comment]
I have done this [example](http://codepen.io/bondifrench/pen/KdLNaV) which is inspired from Chapter 6, using MithrilJs (much terser and lighter than jQuery) and just plain js functions, and a slightly more elaborate one [here](http://codepen.io/bondifrench/pen/NGmXKB) if anybody is interested.
