### ISSUE TITLE
Add tests for exercises

### ISSUE THREAD

**Issue by gyzerok** [MostlyAdequate/mostly-adequate-guide#82]
Requesting to add tests for exercises in the book. So people can test their solutions against these tests.

**Comment by DrBoolean** [comment]
There should be a full test suite with the code?

**Comment by gyzerok** [comment]
I guess [here](https://github.com/DrBoolean/mostly-adequate-guide/blob/master/code/part1_exercises/exercises/curry/curry_exercises.js) for example should be something like this:
```javascript
var input = // some test input data
var output = // result of applying function
var sentences = undefined;
assert(sentences(input), output);
```
This would help to understand what should function do and help to know if you write it right before looking to the answers.

**Comment by DrBoolean** [comment]
https://github.com/DrBoolean/mostly-adequate-guide/blob/master/code/part1_exercises/exercises/curry/curry_exercises_spec.js

Is this not it?

**Comment by DrBoolean** [comment]
Oh oh, i see. You mean, put the test into the book text?

**Comment by gyzerok** [comment]
@DrBoolean I think it would be better if all the exercises could be done without know about github. Just with the book in front of your eyes.

**Comment by gyzerok** [comment]
I can try to rewrite those with such tests inside and without implicit ```support``` functionality.

**Comment by DrBoolean** [comment]
I see now! I'm down for a small experiment
